.github/workflows/build.yml
.github/workflows/build_win.yml

This build in any commits and pull requests.

CI: Add a GitHub Action to build on Windows

---

CMakeLists.txt

This fix build on Debian and Ubuntu systems.
Close #28
Close #8

Make sure to add LLVM_LIBRARY_DIR to link directories

---

.github/workflows/build_linux.yml
.github/workflows/build_win.yml
CMakeLists.txt

Also clean up MSYS2 action and make sure to use latest LLVM version when multiple are installed.

CI: Add a GitHub Action to build on Ubuntu 20.04 LTS

---

README.md
dist/get_deps_archlinux.sh
dist/get_deps_fedora.sh
dist/get_deps_msys2.sh

This PR moves the all in one lists of dependencies to scripts that users can execute. The README is updated accordingly.

create subdir 'dist', update compiling guidelines

---

README.md
dist/get_deps_debian.sh

Tested with Xubuntu 20.04 and Debian testing
(in today's Docker image bitnami/minideb).
Update README.md.

Add script to install dependencies on Debian/Ubuntu.

---

.github/workflows/build.yml
CMakeLists.txt
res/LICENSE.rtf

Allow CMake to generate a proper windows MSI Installer.

Windows MSI Installer

---

source/window.cpp

Small change to enable the built-in imgui keyboard navigation for things like moving around with the arrow keys, opening menus with alt etc.

Enable ImGui keyboard navigation

---

CMakeLists.txt
cmake/build_helpers.cmake
external/ImGui/CMakeLists.txt
external/ImGui/include/imnodes.h
external/ImGui/source/imnodes.cpp
include/views/view_data_processor.hpp
plugins/builtin/CMakeLists.txt
plugins/builtin/source/content/data_processor_nodes.cpp
plugins/builtin/source/plugin_builtin.cpp
plugins/libimhex/include/hex/api/content_registry.hpp
plugins/libimhex/include/hex/data_processor/attribute.hpp
plugins/libimhex/include/hex/data_processor/link.hpp
plugins/libimhex/include/hex/data_processor/node.hpp
plugins/libimhex/include/hex/helpers/shared_data.hpp
plugins/libimhex/include/hex/plugin.hpp
plugins/libimhex/include/hex/providers/overlay.hpp
plugins/libimhex/include/hex/providers/provider.hpp
plugins/libimhex/source/api/content_registry.cpp
plugins/libimhex/source/helpers/shared_data.cpp
plugins/libimhex/source/providers/provider.cpp
source/main.cpp
source/views/view_data_processor.cpp
source/views/view_hexeditor.cpp
source/views/view_pattern.cpp

This PR aims to implement a data processing interface based on nodes using imnodes.

Added Data Processor using Nodes

---

.github/workflows/build.yml
CMakeLists.txt
cmake/build_helpers.cmake

Properly pack all dependencies into nightlies on all platforms

---

source/helpers/plugin_handler.cpp

ImHex segfaulted for me at startup on nixos. adding the check fixed it for me

dont dlclose nullptrs in plugins

---

.gitmodules
.idea/vcs.xml
CMakeLists.txt
external/yara/CMakeLists.txt
external/yara/crypto_mbedtls.h
include/views/view_yara.hpp
plugins/builtin/source/lang/en_US.cpp
source/main.cpp
source/views/view_yara.cpp

This PR aims to add an easy to use interface to match the currently loaded file against a yara rules file and display the results.

Add Yara rule matching interface

---

README.md

Fix path to plugins in readme.

---

plugins/builtin/source/lang/zh_CN.cpp

i18n: Chinese(Simplified)

---

include/views/view_strings.hpp
plugins/builtin/source/lang/de_DE.cpp
plugins/builtin/source/lang/en_US.cpp
source/views/view_strings.cpp

Implement #328 
Use C++-Style Regex -Strings to filter the output

add regex filter in string view

---

plugins/builtin/source/lang/de_DE.cpp
plugins/builtin/source/lang/en_US.cpp
source/views/view_strings.cpp

As requested in #328 the string view now displays the result count

Add result count to string view

---

source/init/tasks.cpp

Fix crash on exit due to not clearing static vector

---

plugins/builtin/source/content/views/view_diff.cpp

Fixed columns in diffing view.

---

lib/external/imgui/include/imgui_memory_editor.h

clipper.Step() should be called in a loop until it returns false.
You don't need to call End() after it.

fix: misuse of clipper

---

plugins/builtin/source/content/welcome_screen.cpp

This issue was visible only for Linux. But when welcome screen and settings are opened, banner image gets corrupted.
It was caused by freeing resource before assigning a new.
In addition, now request for change of the theme is sent only when theme index in settings is actually changed.
And load new banner image when different resource than current is requested.

fix: welcome screen corrupted banner when settings are open

---

plugins/builtin/source/content/pl_builtin_functions.cpp

Hi,
I've added new builtin function to search a sequence within range.

patterns: added find_sequence_in_range function

---

lib/libimhex/include/hex/pattern_language/ast/ast_node_bitfield.hpp
lib/libimhex/include/hex/pattern_language/evaluator.hpp
lib/libimhex/source/pattern_language/pattern_language.cpp

Hi,
I added new pragma `bitfield_order`, so user don't need to add attribute to each bitfield.

patterns: Added bitfield_order pragma

---

plugins/builtin/source/content/welcome_screen.cpp

As mentioned in comments in #447.

ui: fixed theme not changing on startup

---

plugins/builtin/include/content/providers/file_provider.hpp
plugins/builtin/source/content/providers/file_provider.cpp

Linux only.
When mapped file gets modified, kernel sends SIGBUS.
Added proper real time sync for file refresh.

fix: Crash on linux when opened file gets modified

---

.github/workflows/build.yml
.github/workflows/release.yml

Release CI

---

plugins/builtin/source/content/settings_entries.cpp

For some reason json treats unicode string as an array.
Not sure if this a best way, but better than crashing.
edit:
Had to do refactor, user folders didn't load at startup

fix: setting folder tab crash

---

plugins/builtin/source/lang/zh_CN.cpp

i18n: fix typo

---

dist/compiling/windows.md

should read msys2 instead of mys2

Correct minor typo in windows.md

---

.github/workflows/build.yml
.github/workflows/release.yml
README.md
dist/get_deps_fedora.sh
dist/rpm/imhex.spec

Please for the love of all things holy squash the commits here when merging, it's a mess.

Fedora packaging/CI

---

README.md

Add a section about the availability in third party repositories.

Add packaging information

---

lib/libimhex/source/api/imhex_api.cpp
lib/libimhex/source/helpers/fs.cpp

fs: Refactored default path handling

---

.github/workflows/build.yml
CMakeLists.txt
cmake/build_helpers.cmake
lib/libimhex/source/helpers/net.cpp

This fixes #680
I think this need review because I'm not really confident on my changes (due to potencial UB)
This needs testing on Windows

Use the bundled CA in AppImage

---

.github/workflows/build.yml
dist/Brewfile
dist/macOS/0001-glfw-SW.patch

Patch from https://github.com/glfw/glfw/issues/2080#issue-1202549182

added NoGPU dmg for MacOS

---

README.md

`yay install` is not a proper verb

Update AUR instructions

---

dist/Arch/PKGBUILD

As discussed on Discord : https://discord.com/channels/789833418631675954/789833418631675957/1016713453030887524
@Foxboron if you want to take a look ^^

Clean PKGBUILD

---

cmake/build_helpers.cmake

This allows the patterns to be bundled with flatpak version https://github.com/flathub/net.werwolv.ImHex/pull/24

Check ImHex-Patterns directory when IMHEX_OFFLINE_BUILD is set

---

lib/libimhex/include/hex/helpers/fs.hpp
lib/libimhex/source/helpers/fs.cpp
plugins/builtin/source/content/events.cpp
plugins/builtin/source/lang/de_DE.cpp
plugins/builtin/source/lang/en_US.cpp
plugins/builtin/source/lang/it_IT.cpp
plugins/builtin/source/lang/ja_JP.cpp
plugins/builtin/source/lang/ko_KR.cpp
plugins/builtin/source/lang/pt_BR.cpp
plugins/builtin/source/lang/zh_CN.cpp
plugins/builtin/source/lang/zh_TW.cpp

add error message for the file picker

---

lib/libimhex/include/hex/api/content_registry.hpp
lib/libimhex/include/hex/api/task.hpp
lib/libimhex/include/hex/helpers/utils.hpp
lib/libimhex/include/hex/providers/provider.hpp
lib/libimhex/include/hex/ui/imgui_imhex_extensions.h
lib/libimhex/source/helpers/fs.cpp
lib/libimhex/source/ui/imgui_imhex_extensions.cpp
main/include/window.hpp
main/source/window/window.cpp
plugins/builtin/include/content/helpers/pattern_drawer.hpp
plugins/builtin/include/content/providers/disk_provider.hpp
plugins/builtin/include/content/providers/file_provider.hpp
plugins/builtin/include/content/providers/gdb_provider.hpp
plugins/builtin/include/content/providers/intel_hex_provider.hpp
plugins/builtin/source/content/data_visualizers.cpp
plugins/builtin/source/content/helpers/pattern_drawer.cpp
plugins/builtin/source/content/settings_entries.cpp
plugins/builtin/source/content/views/view_find.cpp
plugins/builtin/source/content/views/view_hex_editor.cpp
plugins/builtin/source/content/views/view_information.cpp
plugins/builtin/source/content/views/view_pattern_editor.cpp
plugins/builtin/source/content/views/view_settings.cpp
plugins/windows/source/views/view_tty_console.cpp

This PR fixes various clangd / clang-tidy warnings

fix: Various clang / clang-tidy warnings

---

plugins/builtin/source/content/views/view_about.cpp

Show non existing folders in red in about view

---

lib/libimhex/source/helpers/net.cpp
main/source/init/splash_window.cpp
main/source/init/tasks.cpp
main/source/window/window.cpp

The commit names are self-explanatory
I really would like a code review ^^

Minor additions

---

main/source/init/tasks.cpp
plugins/builtin/source/content/settings_entries.cpp
plugins/builtin/source/lang/de_DE.cpp
plugins/builtin/source/lang/en_US.cpp
plugins/builtin/source/lang/it_IT.cpp
plugins/builtin/source/lang/ja_JP.cpp
plugins/builtin/source/lang/ko_KR.cpp
plugins/builtin/source/lang/pt_BR.cpp
plugins/builtin/source/lang/zh_CN.cpp
plugins/builtin/source/lang/zh_TW.cpp

Add a setting to disable loading of unicode characters

---

plugins/builtin/include/content/views/view_store.hpp
plugins/builtin/source/content/views/view_store.cpp
plugins/builtin/source/lang/de_DE.cpp
plugins/builtin/source/lang/en_US.cpp
plugins/builtin/source/lang/it_IT.cpp
plugins/builtin/source/lang/ja_JP.cpp
plugins/builtin/source/lang/ko_KR.cpp
plugins/builtin/source/lang/pt_BR.cpp
plugins/builtin/source/lang/zh_CN.cpp
plugins/builtin/source/lang/zh_TW.cpp

I think the commit names already explain the changelog

Modifications to Content store

---

main/source/init/tasks.cpp
plugins/builtin/source/content/settings_entries.cpp
plugins/builtin/source/content/welcome_screen.cpp
plugins/builtin/source/lang/de_DE.cpp
plugins/builtin/source/lang/en_US.cpp
plugins/builtin/source/lang/it_IT.cpp
plugins/builtin/source/lang/ja_JP.cpp
plugins/builtin/source/lang/ko_KR.cpp
plugins/builtin/source/lang/pt_BR.cpp
plugins/builtin/source/lang/zh_CN.cpp
plugins/builtin/source/lang/zh_TW.cpp

The principle is that the default value is 2 ("not set") and the popup makes it switch to 1 ("check for updates") or 0 ("do not check for updates") (0 being the default is the popup is closed)
I wasn't sure how to do something cleaner

Ask the users if they want to check for updates

---

lib/libimhex/source/helpers/net.cpp

Not sure if it's worth merging, but this might help users in some cases
It's your call !

Tell the user if he have a proxy set

---

.github/workflows/build.yml
dist/rpm/imhex.spec

Commits https://github.com/WerWolv/ImHex/commit/91a4f52f67bdc955268131d0a67d41400a2bd40f https://github.com/WerWolv/ImHex/commit/0d09c24840114cd3a9871be83795a6360fb8c6a3 and https://github.com/WerWolv/ImHex/commit/cbd7c10f3dee8bafa1045b711013087ef43f060d apparently fixed LTO in Linux, so here is a pull request to enable it
Ref https://github.com/WerWolv/ImHex/issues/610

CI: Enable LTO on Linux

---

.github/workflows/build.yml
.github/workflows/release.yml
dist/AppImageBuilder.yml
dist/Arch/PKGBUILD

Follow up to #861 
I also renamed `imhex-1.26.2-win64.msi` to `imhex-1.26.2-Windows.msi`

add architecture to artifacts

---

.github/workflows/tests.yml

I'd recommend letting the tests run before merging this one, just to be sure

do not run `make install` for tests

---

.github/workflows/build.yml
dist/rpm/imhex.spec

re-enable Fedora rawhide builds

---

plugins/builtin/source/content/views/view_find.cpp

`\r` and `\n` need to be filtered.

Adjust spaces and lineFeeds

---

plugins/builtin/include/ui/pattern_drawer.hpp
plugins/builtin/source/ui/pattern_drawer.cpp

This requires https://github.com/WerWolv/PatternLanguage/pull/34 to be merged first, and then this can be amended to update the submodule and merged to add support for the new features.

Update pattern_language and implement support for new bitfield features

---

plugins/builtin/include/content/providers/file_provider.hpp
plugins/builtin/source/content/providers/file_provider.cpp

 add FileProvider::invalidateFiles()

---

lib/libimhex/include/hex/api/event.hpp
lib/libimhex/include/hex/api/imhex_api.hpp
lib/libimhex/include/hex/providers/provider.hpp
plugins/builtin/source/content/events.cpp
plugins/builtin/source/content/welcome_screen.cpp

This PR adds some documentation. It's actually pretty random, I followed the function calls I was curious about and commented whenever I wasn't sure/I thought it needed clarification
You might want to make sure to squash them, because the commits are kind of a mess, I didn't went through the effort of interactive rebase

Add some documentation

---

plugins/builtin/source/content/welcome_screen.cpp

Allow to remove recent providers with right click

---

lib/libimhex/include/hex/helpers/utils_macos.hpp
lib/libimhex/source/helpers/utils_macos.m
main/include/window.hpp
main/source/init/splash_window.cpp
main/source/window/linux_window.cpp
main/source/window/macos_window.cpp
main/source/window/win_window.cpp

Draft because I want to test it again tomorrow with all OSes, first

Add a native error message when glfw window creation fails

---

lib/libimhex/include/hex/api/event.hpp
main/CMakeLists.txt
main/include/crash_handlers.hpp
main/include/window.hpp
main/source/crash_handlers.cpp
main/source/main.cpp
main/source/window/window.cpp

Draft because I absolutely do not trust myself writing good code at 2AM. I will review it tomorrow

Handle crashes that may happen before the main loop

---

plugins/builtin/source/content/views/view_hex_editor.cpp

Set the Begin field to the current selected address

PopupSelect: consider selected address

---

plugins/builtin/source/ui/hex_editor.cpp

fix https://github.com/WerWolv/ImHex/issues/1146
related https://github.com/WerWolv/ImHex/commit/3a840c4ceddd050371d744761b0194ffcbfe7773

fix: wrong lineStartAdresses for custom encoding characters

---

plugins/script_loader/source/plugin_script_loader.cpp

- Added reload feature for dotnet scripts
- Added a thread that reloads on menu open

Add reload feature for scripts

---

plugins/builtin/romfs/lang/en_US.json
plugins/builtin/source/content/ui_items.cpp

add "Hold SHIFT for more info" text to provider tooltip

---

plugins/builtin/source/content/providers/disk_provider.cpp

- Fixed disk provider not working for linux
- Used ioctl instead of fstat
- Fixed buffer issues

Fix linux disk provider

---

.github/workflows/build.yml

There are unused ImHex-specific flags in the custom GLFW build on MacOS. Also, it isn't built in release mode

fix things on the custom GLFW build

---

lib/libimhex/source/helpers/magic.cpp

This PR fix libmagic dumping files in the imhex cwd when compiling them
This code was actually written by you (notice the source branch), this PR is just a reminder that the fix works and you can merge it ^^

fix: Hopefully fix magic compile dumping files into cwd

---

plugins/builtin/source/content/tools_entries.cpp

Supersedes #1240 - depends on #1249 and https://github.com/WerWolv/libwolv/pull/8 to work.

Selectable demangler

---

plugins/builtin/source/content/providers/file_provider.cpp

Ref #1210 
Call [`SetFileTime()`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfiletime) everytime `FileProvider::save()` is called.
I moved the call to `File::close()` from `FileProvider::open()` to `FileProvider::close()` because `SetFileTime()` requires a file handler as input, so I need `File::m_file` to be valid.

fix: update timestamp when saving a file in windows

---

plugins/builtin/source/content/views/view_store.cpp

fix: verify that file names queried from the store do not allow path traversal

---

main/include/init/splash_window.hpp
main/include/window.hpp
main/source/init/splash_window.cpp
main/source/main.cpp
main/source/window/window.cpp

Currently in windows, the loop() functions handle the loop (and everything timing related), and the frame logic.
I separated the frame logic in a new `fullFrame()` function
Needed for #1299

refactor: separate loop and frame logic

---

plugins/builtin/source/ui/pattern_drawer.cpp

This will simplify the codebase in the pattern drawer. It returns early on conditional statements and reduces the amount of nested code making it easier to read and track while developing.

Return early to remove nested code

---

.github/workflows/build.yml
CMakeLists.txt
cmake/build_helpers.cmake
dist/compiling/macos.md

This PR is simply a refactor, to clarify these flags that shouldn't impact anything

refactor: replace CREATE_BUNDLE and CREATE_PACKAGE with IMHEX_GENERATE_PACKAGE

---

SECURITY.md

Your outdated handle was mentioned on the security page, it also appears to break Githubs markdown renderer for some unknown reason.

Fix broken handle in Security.md

---

lib/libimhex/include/hex/ui/toast.hpp
plugins/builtin/include/ui/pattern_drawer.hpp
plugins/builtin/source/content/views/view_data_inspector.cpp
plugins/builtin/source/content/views/view_pattern_editor.cpp
plugins/builtin/source/ui/pattern_drawer.cpp

Revert pattern language until it's stable again

---

.github/workflows/tests.yml
plugins/builtin/romfs/lang/en_US.json
plugins/builtin/source/content/out_of_box_experience.cpp
tests/check_langs.py

This script will be executed on every CI run as part of tests, and will ensure no unlocalised strings are present in the code
Note that texts without the `_lang` suffix will not be checked, e.g. https://github.com/WerWolv/ImHex/blob/96fe608d608e4deecd538bfa1fa92471f91649e0/plugins/builtin/source/content/views/view_provider_settings.cpp#L10

test: add script to check localized texts occurences in code

---

main/gui/source/messaging/win.cpp
plugins/builtin/source/content/providers/process_memory_provider.cpp

Commits should be self-explanatory

fix: remove TODO + show error message when reading/write in process provider

---

dist/web/compose.yml

Nothing significant in this PR, just a simple error in the docker compose example command

doc: fix --build flag in web docker compose

---

dist/web/source/index.html
dist/web/source/wasm-config.js

This PR adds a progress bar to the web version
Credits to https://github.com/WordPress/wordpress-playground/pull/46 for the original idea, although it had to be modified
Link: https://github.com/emscripten-core/emscripten/issues/16278

feat: Add progress bar to web version

---

.github/workflows/build.yml
cmake/build_helpers.cmake
cmake/modules/PostprocessBundle.cmake
dist/rpm/imhex.spec

build: Hopefully fix macOS x86 build issues

---

lib/libimhex/include/hex/api/event_manager.hpp
main/gui/source/window/window.cpp
plugins/builtin/include/content/popups/popup_crash_recovered.hpp
plugins/builtin/romfs/lang/en_US.json
plugins/builtin/source/content/events.cpp

This PR improves many things which can be seen by the commit name, but the most important thing is the addition of a popup telling the user when an exception is thrown

Improve error recovery

---

plugins/ui/CMakeLists.txt

This will fix unit tests currently failing
Discord discussion: https://discord.com/channels/789833418631675954/789840633414025246/1213813272713764924

fix: fix ui plugin linking to pl when libimhex already does it

---

.github/workflows/build.yml

Fix GeekyEggo/delete-artifact failing in PRs
https://github.com/GeekyEggo/delete-artifact/issues/25

fix: Fix MacOS packaging workflow in PRs

---

README.md
lib/libimhex/include/hex/helpers/utils.hpp
lib/libimhex/source/api/theme_manager.cpp
lib/libimhex/source/helpers/patches.cpp
plugins/builtin/source/content/data_inspector.cpp
plugins/builtin/source/content/popups/hex_editor/popup_hex_editor_find.cpp
plugins/builtin/source/content/views/view_bookmarks.cpp
plugins/builtin/source/content/views/view_find.cpp
plugins/builtin/source/content/views/view_hex_editor.cpp
plugins/ui/source/ui/hex_editor.cpp
tests/algorithms/source/endian.cpp

fix 40 typos
`endianess` => `endianness`

Fix 40 typos

---

plugins/diffing/source/content/views/view_diff.cpp

Fix diffing view's "end" display

---

.github/workflows/tests.yml

This PR adds some test with both `plcli` and `imhex --pl` to make sure they somewhat work

test: Add plcli integration tests

---

lib/libimhex/include/hex/providers/provider.hpp

doc: remove hex.builtin.provider.memory name

---

.github/codecov.yml
.github/workflows/tests.yml

Repository: https://app.codecov.io/gh/WerWolv/ImHex
(This PR should be squashed)

test: Add code coverage support with CodeCov

---

.github/workflows/build.yml

git: Remove Fedora 38 and add Fedora 40

---

CMakeLists.txt

build: update CMakeLists.txt

---

.github/workflows/release.yml

This should fix our release CI
See https://github.com/KSXGitHub/github-actions-deploy-aur/issues/39

fix: Remove DSA key from AUR deploy action

---

plugins/builtin/romfs/lang/en_US.json
plugins/builtin/source/content/tools/ieee_decoder.cpp

Added a quarter precision (8 bits) button to IEEE 745 tool.

---

lib/libimhex/include/hex/helpers/tar.hpp

chore: update tar.hpp

---

resources/dist/macos/Info.plist.in

seem to fix #1809. I couldn't build the app, so hoping that's the right place to update resulting `Info.plist`

Fix macos blurry flicker

---

lib/libimhex/source/ui/imgui_imhex_extensions.cpp
plugins/hashes/source/content/hashes.cpp

#1974 - [Bug] CRC64 parameters are limited to 32bit

---

plugins/builtin/source/content/views/view_pattern_editor.cpp

Another battle with tabs. Hopefully the last.

---

dist/macOS/arm64.Dockerfile
dist/macOS/arm64.crosscompile.Dockerfile

it also updated ubuntu to 24.04

build: Make MacOS arm64 build use clang 19

---

dist/compiling/macos.md

Brewfile has moved from `dist/Brewfile` to `dist/macOS/Brewfile`.
Updated build instructions to reflect this previous change
N/A
N/A

Update macOS compile instructions as Brewfile has moved

---

lib/libimhex/source/helpers/logger.cpp
main/gui/source/init/splash_window.cpp
plugins/builtin/source/content/data_inspector.cpp
plugins/builtin/source/content/providers/file_provider.cpp

Sister (or brother?) pull request to https://github.com/WerWolv/PatternLanguage/pull/163, that update `libfmt` to 11.2.0.
Solve #2225.
You may want to look closer to `plugins/builtin/source/content/data_inspector.cpp` and `plugins/builtin/source/content/file_provider.cpp` because the calls here are wrapped around `try / catch` with `fmt::format_error` (for the first) and `std::exception` for the second.
Thanks for the app!

Update libfmt to 11.2.0

---

lib/third_party/imgui/imgui/source/misc/freetype/imgui_freetype.cpp
plugins/fonts/include/font_atlas.hpp
plugins/fonts/source/font_loader.cpp

ALso made ascender return ascender value.

fix: font sizes did not match what other apps render.

---

plugins/builtin/romfs/lang/zh_CN.json
plugins/diffing/romfs/lang/zh_CN.json
plugins/disassembler/romfs/lang/zh_CN.json
plugins/fonts/romfs/lang/zh_CN.json
plugins/hashes/romfs/lang/zh_CN.json
plugins/ui/romfs/lang/zh_CN.json
plugins/visualizers/romfs/lang/zh_CN.json

Updated [plugins/builtin/romfs/lang/zh_CN.json](https://github.com/only9464/ImHex/blob/master/plugins/builtin/romfs/lang/zh_CN.json)、 [plugins/diffing/romfs/lang/zh_CN.json](https://github.com/only9464/ImHex/blob/master/plugins/diffing/romfs/lang/zh_CN.json)、 [plugins/disassembler/romfs/lang/zh_CN.json](https://github.com/only9464/ImHex/blob/master/plugins/disassembler/romfs/lang/zh_CN.json)、 [plugins/fonts/romfs/lang/zh_CN.json](https://github.com/only9464/ImHex/blob/master/plugins/fonts/romfs/lang/zh_CN.json)、 [plugins/hashes/romfs/lang/zh_CN.json](https://github.com/only9464/ImHex/blob/master/plugins/hashes/romfs/lang/zh_CN.json)、 [plugins/ui/romfs/lang/zh_CN.json](https://github.com/only9464/ImHex/blob/master/plugins/ui/romfs/lang/zh_CN.json)、 …

i18n: update Chinese (Simplified) translations

---

.github/workflows/build.yml

This pr updates the pattern language library to include two fixes. 
The first fix deal with local variables that are children of a structure, a union, a bitfield or an array losing their offsets when the parent's `setOffset()` is called. 
The second fix is that local variables of unions were being used as size contributors of the patterns place with said unions.  
Further details may be found in the pattern language pull requests for the files listed as changed in the PL submodule in this pr.

patterns: Updated pattern language

---

plugins/ui/source/ui/hex_editor.cpp

The scrollbar, mini map and the segment delimiters were also using the incorrect bytes per row value when changing data size forced a change in the number of bytes per row. From the definition of the new value it follows that bytesPerRow/bytesPercell == m_bytesPerRow/bytesPerCell, so it is not necessary to switch it when it is divided by that quantity.

fix: more problems with bytes per row.

---

.github/workflows/build.yml

ci: fix rpm ccache

---

lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp

Also fixed  tab insertion on selections.

feat: added paren and quote autocompletion.

---

plugins/builtin/romfs/lang/en_US.json
plugins/ui/include/ui/text_editor.hpp
plugins/ui/source/ui/text_editor/editor.cpp
plugins/ui/source/ui/text_editor/navigate.cpp
plugins/ui/source/ui/text_editor/render.cpp
plugins/ui/source/ui/text_editor/support.cpp
plugins/ui/source/ui/text_editor/utf8.cpp

Attempt to fix WerWolv's strange off by one problem when using the mouse. Added a popup question for files that contain long lines (>1024 bytes). Also improved the handling of large lines, so it won't stall the app. May also contain other smaller issue fixes.

Fixes for next release.
