WerWolv/ImHex

- source/views/view_data_inspector.cpp
- source/views/view_hexeditor.cpp
The `time_t` decoding fix only actually affected the windows codepaths. The copy hex bytes bug manifested for me by sometimes copying too many bytes because the vector did not place its null terminator correctly.
> a few bugfixes

- CMakeLists.txt
- source/helpers/loader_script_handler.cpp
This remove the hardcoded version in CMakeLists.txt and loader_script_handler.cpp.
Fixing building on Arch Linux and probably other systems.
> Detect python version at build time

- include/helpers/disassembler.hpp
- include/views/view_disassembler.hpp
- source/views/view_disassembler.cpp
This allows to support older version of Capstone (example 4.0.1).
Should help with ubuntu building issues (Still need to fix LLVM linking issue)
Linked issue #8
> Abstract capstone architectures

- README.md
Tested in a fresh Fedora 33 Docker container.
> Add a list of packages to install for building on Fedora 33

- dist/get_deps_archlinux.sh
After running `sh get_deps_archlinux.sh` then `cmake ..` in the build folder, got `None of the required 'glm' found`. This fixes that
> add glm to arch deps

- dist/get_deps_fedora.sh
Due to differences in package names between Deb based systems, Arch
Linux, and RPM based systems the package containing the development
headers for file were missing from the Fedora dependencies script.
This includes the package `file-devel`, which is the package which
resolves the issue.
In Fedora, one can identify the package providing a specific file using
the verb "whatprovides" with the command dnf, e.g.:
[~]$ dnf whatprovides /usr/include/magic.h
Last metadata expiration check: 4 days, 0:23:05 ago on Fri 04 Dec 2020 09:06:53 AM PST.
file-devel-5.39-3.fc33.i686 : Libraries and header files for file development
Repo        : fedora
Matched from:
Filename    : /usr/include/magic.h
file-devel-5.39-3.fc33.x86_64 : Libraries and header files for file development
Repo        : @System …
> dist/fedora: Include file magic headers

- CMakeLists.txt
This fix openSUSE and Gentoo issue mentioned in https://github.com/WerWolv/ImHex/issues/37#issuecomment-739503138.
(tested on openSUSE tumbleweed via Docker)
I also took the liberty of renaming llvm_lib to llvm_demangle_lib to be more specific in the ``CMakeLists.txt``.
> Support non standard LLVM library names

- .github/workflows/build.yml
This PR adds nightlies for both Windows and Linux so all three supported platforms now also have nightlies
> Nightly support for Windows and Linux

- source/lang/builtin_functions.cpp
Hi! A little fix to make `findSequence` works as described :)
> fix(lang): fixes occurrence index in findSequence built-in function

- CMakeLists.txt
- plugins/libimhex/include/helpers/utils.hpp
- source/views/view_hexeditor.cpp
Hello,
This pull request fixes build error on FreeBSD. The added lines are conditional and they do not affect build on other operating systems.
On FreeBSD, libcrypto is installed by default but pkg-config related files are not installed.
So it is necessary to use find_library instead of pkg_search_module in CMakeLists.txt.
> Fix build on FreeBSD

- CMakeLists.txt
- source/views/view_help.cpp
If the _.git_ folder is not present during the build, the about page will contain an uninformative line because `GIT_BRANCH` and `GIT_COMMIT_HASH` are empty. This may happen if the source code is downloaded from the releases page or is exported with `git archive`.
> Show commit on about page only if available

- dist/ImHex-9999.ebuild
Gentoo doesn't have a community package set like the AUR, so it'd be handy to make this available here if you like.
> Add a Gentoo ebuild

- README.md
Just realized I forgot to update the README with the fixed location of configuration files.
> Fix new linux file locations in README

- source/main.cpp
This is necessary to fix the bad any_cast error that occurs otherwise.
> Fix passing path through argv

- README.md
This change is to reflect the commit made in 785ecb8a7858edfb88747623b7437da0c02b5317, which changes openssl libcrypto to libmbedtls, making changes everywhere except in the README documentation.
This seems to be the root of the issue in #171 and #113 (see the very last comment made)
May also be nice to update the CMake files to make a more friendlier error message (not added here)
> Update deps in README

- plugins/builtin/source/content/settings_entries.cpp
- plugins/libimhex/include/hex/api/content_registry.hpp
- plugins/libimhex/source/api/content_registry.cpp
- source/views/view_data_processor.cpp
- source/views/view_pattern.cpp
- source/window.cpp
getSetting now returns a straight nlohmann::json instead of an optional.
If the data isn't present, it will return a json null.
All accesses to the settings will first check that the data has the
expected type.
> Fix various crashes on bad settings data.

- source/views/view_pattern.cpp
Many of the default directories searched for mgc files do not actually exists into some systems (e.g. `/usr/share/ubuntu/imhex/`), which is setting error to non-zero error code so mgc files end up ignored.
> Fix: ignore non-existent magic directories

- .github/workflows/build.yml
CMake [seems to have trouble](https://stackoverflow.com/questions/34208360/cmake-seems-to-ignore-cmake-osx-deployment-target) setting the minimum macOS target unless it's done just right. This change sets an environment variable so it will get picked up directly, instead of through cmake.
> Setting an env var for macOS 10.15 support

- plugins/libimhex/CMakeLists.txt
The flag tells the compiler the minimum OS the app is allowed to run on. Unless you have a particular API you're trying to use, it's best to set it to as old an OS as possible (so as many users can use it as possible.) Until a couple days ago it was set to 11.0. Changing it to 10.15 opens the app up to users still running macOS Mojave (10.15.x)
This PR removes the flag specifically for the libimhex dylib, which will now pull this value from the env var that is declared in the build script.
> Drop deployment target flag from libimhex plugin

- cmake/modules/PostprocessBundle.cmake
- plugins/libimhex/source/helpers/utils_mac.mm
- source/helpers/plugin_manager.cpp
- source/window.cpp
The loading of `builtin.hexplug` was causing the runtime also load `libimhex.dylib` as specified by the path `@rpath/libimhex.dylib`. The macOS runtime to looks up the array of rpaths (runtime paths) within the application binary itself in an attempt to discover and load the `libimhex.dylib`. Unfortunately the binary had no rpaths specified, and the runtime would either find no `libimhex.dylib` (causing the plugin to fail to load) or a _totally different_ `libimhex.dylib` than the one inside the application bundle (causing ODR violations and all kinds of other strange behaviors.)
The fix here is to inject an rpath into the imhex binary that causes `@rpath/libimhex.dylib` to resolve to the `libimhex.dylib` embedded within the application bundle. This will cause the runtime to realize that …
> Add rpath to binary executable on macOS

- source/views/view_hexeditor.cpp
The current behavior shows the extension in the file dialog as being "hexproj", however it will still allow you to use the *.hexproj filter in order to save files without the hexproj extension. This results in an unintuitive save behavior where it appears it will save with an extension even if one is omitted, but the result is actually saving without an extension. Combined with 'open project' having a *.hexproj filter as well, it gives an initial appearance of not having saved your file. 
* NFD doesn't (afaict) have a means of checking which filter you were using when saving, meaning if you manually select "All Files" this change will still append ".hexproj" to your filename
* This would mean saving with an extension other than .hexproj would be unsupported
> Ensure projects have .hexproj extension on save

- source/views/view_help.cpp
- source/views/view_hexeditor.cpp
- source/views/view_pattern_editor.cpp
Manjaro and presumably other systems have started adding the `-Werror=format-security` flag, causing the build to fail.
It might make sense to add the `-Werror=format-security` flag to the compiler flags given how easy it is to keep it happy.
Fixes #245 and #295
> warnings: fix format-security warnings

- dist/get_deps_debian.sh
The "!" parameter to if needs to be free-standing. As is the script always outputs this on Ubuntu 20.04:
./get_deps_debian.sh: 8: !which: not found
> Fix typo in Debian/Ubuntu dependencies script

- CMakeLists.txt
- plugins/libimhex/CMakeLists.txt
When compiling using system libraries, the name used for linking are all wrong and result in lots of link errors.
Thus, this PR fixing the lib names used for linking by using the CMake variables when available or correct lib names.
> build: Fix system libraries usage

- source/window/window.cpp
ImHex catch the SIGABRT but the signal handler raising the same signal makes the whole thing doing an infinite call loop (SIGABRT -> sighandler -> raise SIGABRT -> SIGABRT -> sighandler -> etc.)
The fix is simply to unregister the signal handler when catching a signal, as it terminates the whole program with SIGABRT anyway (maybe re-raising the same signal instead of SIGABRT?)
> Fix infinite loop on signal handling.

- source/views/view_hexeditor.cpp
`View > Hex Editor > (highlight some bytes) > (right click) > Copy as... > Rust Array` copies code formatted like in the following example: 
```rust
let data: [u8, 16] = [ 0x54, 0x4F, 0x4B, 0x49, 0x4D, 0x45, 0x4B, 0x49, 0x20, 0x43, 0x55, 0x4C, 0x20, 0x20, 0x00, 0x80 ];
```
However, this is incorrect. the type of this array should be `[u8; 16]`, not `[u8, 16]`. For the above example to compile in rust, the above example would have to look like: 
```rust
let data: [u8; 16] = [ 0x54, 0x4F, 0x4B, 0x49, 0x4D, 0x45, 0x4B, 0x49, 0x20, 0x43, 0x55, 0x4C, 0x20, 0x20, 0x00, 0x80 ];
```
> Fix syntax error when copying rust array to clipboard

- external/yara/CMakeLists.txt
Build libyara with fPIC, fixes #340 without breaking the embedded spash screen.
> fix build on Fedora 35 (#340)

- external/ImGui/include/imgui_impl_opengl3_loader.h
- external/ImGui/source/imgui_impl_opengl3.cpp
Switch from `GL_LINEAR` to `GL_NEAREST` for font texture upscaling.
This makes the bitmap font crisp on hidpi displays (tested on a retina Macbook Pro 14", 2021)
This needs further testing on other configurations - it's plausible that I've made other usecases worse.
Before:
After:
> ImGui: Nearest-Neighbour Font Upscaling

- .github/workflows/build.yml
This PR uses option 'pacboy' of setup-msys2 in order to install build dependencies, and take advantage of setup-msys2's caching feature.
> ci/win: use option 'pacboy' of setup-msys2 to install dependencies

- include/init/splash_window.hpp
- plugins/libimhex/include/hex/helpers/shared_data.hpp
- plugins/libimhex/source/api/imhex_api.cpp
- plugins/libimhex/source/helpers/shared_data.cpp
- source/init/splash_window.cpp
- source/main.cpp
- Fixes WerWolv/ImHex#373 on Linux
ImHex does not restart properly due to missing environment variables
```
[ERROR] GLFW Error [65544] : X11: The DISPLAY environment variable is missing
[FATAL] Failed to initialize GLFW!
```
#373 seems to have different issues on macOS though
> Store environment variables and use on restart

- plugins/builtin/source/content/providers/file_provider.cpp
- plugins/libimhex/source/providers/provider.cpp
The file save functionality is currently broken on Linux. This patch fixes it, but note that saving a file does not set `ProjectFile::s_hasUnsavedChanged` to `true`, so the dirty indicator `(*)` stays in the title bar. I don't know what project files are used for so I'm not sure what the expected behavior here is.
> Fix saving files

- README.md
I added a line with a few commands to help sort out issues with building on macOS. `brew doctor` will complain about not updated SDKs etc. I purposely kept it short, because it's just a hint. Let me know if I should refine it (I would then maybe put it in the wiki)
> add hints to debug build failures

- main/source/init/splash_window.cpp
When building ImHex in debug mode outside of a git repo, the build would fail due to missing GIT_ variables.
> Fix DEBUG without GIT_* variables defined

- plugins/builtin/source/content/data_processor_nodes.cpp
- NodeBufferSlice would always error because the bounds condition had the wrong operator
- NodeCastBufferToInteger would produce weird values if the source buffer didn't completely fill the integer.
- Also made a small refactor to number constant processing
> nodes: Validate some buffer operations

- lib/libimhex/source/helpers/file.cpp
- plugins/builtin/source/content/welcome_screen.cpp
Event posting triggers updating `s_recentFilePaths`, which replaces list elements after uniqueness check. It lead to a segfault
> fix: don't change list while iteration

- plugins/builtin/source/content/providers/file_provider.cpp
When opening a file that you do not have write access to, the file provider will first open the file for reading and writing, discover it does not have permission, then attempt to open the file for reading only. This works as intended. Then, mmap is called with the PROT_WRITE flag which is forbidden, as the file was opened for reading (see `mmap(2)`). Finally, the if condition to check if mmap failed checks if mmap returned a null pointer, which it never will (instead returning `MAP_FAILED` or `(void *)-1` if an error occurred).
This PR removes the PROT_WRITE flag from the mmap call if the file is opened for reading, and properly checks if the mmap call failed.
> fix: Prevent segfault when opening a file w/o read access (linux)

- lib/libimhex/include/hex/pattern_language/ast_node.hpp
- lib/libimhex/include/hex/pattern_language/pattern_data.hpp
Added a few little things.
Fixed color attributes not working on static arrays/structs.
Added new attribute `single_color`, this attribute sets same color for all elements inside struct, basically color per struct.
`color` and `single_color` attributes can now be set for struct definitions if user wishes so.
> pattern: add single_color attribute, fixed static array color override

- lib/libimhex/source/pattern_language/preprocessor.cpp
1. Read an include filename until the end of the line
2. Correctly check a file existence
> Fix crash on typing "#include "

- lib/libimhex/include/hex/api/content_registry.hpp
- lib/libimhex/source/api/content_registry.cpp
- lib/libimhex/source/helpers/paths.cpp
- plugins/builtin/source/content/settings_entries.cpp
- plugins/builtin/source/content/views/view_settings.cpp
- plugins/builtin/source/lang/en_US.cpp
Helo.
Created new setting category, where user can specify custom directories.
Custom dirs are only used for patterns, pattern includes, python scripts, magics, yara rules, constants and encodings.
Main reason is that anyone might want to use multiple git repos or sources for such files.
Not implemented for macos, because it uses only one path, but can be implemented as well.
Also added ux change, where setting categories are sorted the way they were actually created instead of alphabetical order.
Tested on linux.
> feature: User now can add custom directories

- lib/libimhex-rs/Cargo.lock
- lib/libimhex-rs/Cargo.toml
- lib/libimhex-rs/build.rs
- lib/libimhex-rs/src/bookmarks.rs
- lib/libimhex-rs/src/imhex.rs
- lib/libimhex-rs/src/imhex_api.rs
- lib/libimhex-rs/src/lib.rs
- lib/libimhex/include/hex/api/imhex_api.hpp
* Restructure and rename parts of library to better fit idiomatic Rust
* Add documentation to the items in the library
* Move from just cxx to autocxx (while falling back to cxx for a function which autocxx has an issue detecting all the overloads of)
* General cleanup
* Have bookmark API use Rust-native Range type for describing regions
> Rework libimhex-rs to use autocxx

- .github/workflows/build.yml
I pinned the version of appimage-builder in the CI since the latest version seems to have a bug that makes the CI fails
Related issue : https://github.com/AppImageCrafters/appimage-builder/issues/227
> Fixed CI failing with AppImages

- dist/AppImageBuilder.yml
This fixes #507
This PR simply fix the libicu* version number to 66 instead of 67 (The Ubuntu version used is still 20.04)
> fixed libicu version for AppImages

- dist/imhex.desktop
For #511 the path is `/app/bin/imhex` so hardcoding is bad. The categories looked like copy and paste. I went the `Development;IDE;`. An alternative would be `Utility;TextEditor;` however I don't think it does the project justice.
> Fixed the .desktop file

- plugins/builtin/source/lang/pt_BR.cpp
Hi,
wondered why my "Datei"-menu (german language selected in settings) got mixed with brazilian items after updating ImHex. The new brazilian language file overwrites the fallback language from english to brazilian. I don't think this was done on purpose ;)
> revert fallback lang

- dist/AppImageBuilder.yml
the problem comes from library to load svg files, which isn't used in the Ubuntu (22.04 XFCE IIRC ?) used to generate AppImageBuilder.yml (so the package containing it is not included), but required on some systems like my ArchLinux KDE
> Appimage file chooser crash

- plugins/builtin/include/content/views/view_pattern_editor.hpp
- plugins/builtin/source/content/views/view_pattern_editor.cpp
A few things.
1. Added recursive pattern scan for mime lookup
2. In variable weren't working/crashing because of cleaning before eval, also in-vars disappeared after eval from settings.
3. Removed some dead code.
> fix: invariables not working, add recusive pattern scan

- lib/libimhex/source/helpers/fs.cpp
fix not saving to "XDG_DATA_HOME", when "XDG_DATA_DIRS" is available.   
In flatpak, downloaded `libraries/patterns` will be saved to `/run/host/user-share/imhex`, which will be cleared when app exit.  
> XDG specification specifies how to find config and data directories on linux systems. Specifically, it says this:
> - Data should be written to $XDG_DATA_HOME
> - Config should be written to $XDG_CONFIG_HOME
> - Data should be read from $XDG_DATA_HOME:$XDG_DATA_DIRS
> - Config should be read from $XDG_CONFIG_HOME:$XDG_CONFIG_DIRS
> Fix "Content Store" persist in flatpak.

- README.md
Fix required due to CI changes in df94370598514d786c2faf101eda22c71fd9926a
> git: Fix link to latest Fedora RPM in README

- .github/ISSUE_TEMPLATE/bug_report.yaml
- lib/libimhex-rs/imgui-rs/src/drag_drop.rs
- lib/libimhex-rs/imgui-rs/src/draw_list.rs
- lib/libimhex-rs/imgui-rs/src/fonts/atlas.rs
- lib/libimhex-rs/imgui-rs/src/input/mouse.rs
- lib/libimhex-rs/imgui-rs/src/input_widget.rs
- lib/libimhex-rs/imgui-rs/src/lib.rs
- lib/libimhex-rs/imgui-rs/src/string.rs
- lib/libimhex-rs/imgui-rs/src/style.rs
- lib/libimhex-rs/imgui-rs/src/tables.rs
- lib/libimhex-rs/imgui-rs/src/widget/color_editors.rs
- lib/libimhex-rs/imgui-rs/src/widget/selectable.rs
- lib/libimhex-rs/imgui-rs/src/window/child_window.rs
Readability fixes focused in the `lib/libimhex-rs/imgui-rs/.rs` path
Summary:
- Doc alias readability improvements are in one commit
- Comment readability improvements are in a separate commit
- There was also a small fix in the bug report yaml that didn't make sense for a separate PR
> refactor(imgui-rs): Rust code readability improvements

- lib/external/imgui/source/TextEditor.cpp
Small change to fix issue #590, as I'd noticed the behaviour previously.
Only tested on Windows at the moment.
> Fixes issue #590

- lib/libimhex/CMakeLists.txt
This update to NFD Extended fixes the deployment target detection so we no longer need to pass the `NFD_USE_ALLOWEDCONTENTTYPES` flag manually.  NFD Extended now detects the correct deployment target that was set by the `MACOSX_DEPLOYMENT_TARGET` export.
> build: Update nfd-extended to get correct feature test detection

- main/source/window/window.cpp
This avoids a crash on POSIX after running a command from the command
pallete; on completion, a SIGCHILD will be raised, which was incorrectly
calling the error handler and terminating ImHex.
> Explicitly connect to desired signals, rather than every one.

- .github/workflows/build.yml
- dist/rpm/imhex.spec
This PR adds very small fixes directed at Fedora :
- use 'imhex' as package name in imhex.spec, so it's the same name as in the official Fedora repository (it's weird to have "imhex" in the official repository and "ImHex" with the github rpm, plus I think this allowed both packages to be installed at the same time, which I don't think is a good thing)
- Remove CMakeCache cache in the CI : it doesn't work as of now, and after thinking about it, CMake is handled by rpmbuild and not us, which I think makes it risky to try to manage it (by caching it)
> Small fixes for Fedora

- CMakeLists.txt
As per cmake.org/cmake/help/latest/prop_tgt/CXX_STANDARD.html,
`set(CMAKE_CXX_STANDARD 23)` requires minimum cmake version bump to 3.20
> Update CMakeLists.txt minimum required cmake version

- lib/libimhex/CMakeLists.txt
to allow building against RHEL 9's system curl
> lower curl version requirement

- .github/workflows/build.yml
- CMakeLists.txt
The pull request to change the install directory structure/add support for Fedora introduced a bug in the CI, essentially caused by the fact that the deb and AppImage version shared the same build directory (I was updating the build directory of the deb with a flag for the appimage).
This caused the cache to not be taken into account for the appimage build (I don't know why), thus rebuilding everything
> Fix "build twice" bug in the CI

- plugins/builtin/source/content/views/view_pattern_data.cpp
App crashed when pattern was evaluating caused by race condition resulting in SEGV.
Fix might be a bit crude.
> fix: crash when evaluating patterns

- .github/workflows/build.yml
The "PORTABLE" file is currently empty, which might confuse users about its presence.
This PR adds a simple text to indicate its purpose to users
> add text to the PORTABLE file

- .github/workflows/build.yml
- README.md
This PR :
- Change deb name to include "Ubuntu 22.04"
- Change the README to explicitely tell people other distributions are supported through the AppImage
> Change Ubuntu package name + README update

- plugins/builtin/source/content/views/view_data_inspector.cpp
Fixes the issue discussed on #760
> Fix: bad optional access when inspectors.hexpat is missing

- dist/Dockerfile
According to DockerFile reference: https://docs.docker.com/engine/reference/builder/#maintainer-deprecated
The MAINTAINER flag is now deprecated, as such I turned it into a label flag as shown in https://docs.docker.com/engine/reference/builder/#label
> Fix deprecated MAINTAINER flag.

- .github/workflows/analysis.yml
- .github/workflows/build.yml
- .github/workflows/tests.yml
This PR uses a cache action to manage ccache. This allows to easily set a cache size limit (I think this is why builds are taking so long right now), and print statistics after the run to show if the cache worked
Other minor changes :
- Remove Rust and libpython from the CI, as discussed on discord
- Fix the cache key name for MacOS, this caused the normal/NoGPU build caches to mix up, and slow down the build
- Do not pin appimage-builder version anymore as the issue we faced with it was resolved in the latest release
> CI: Use action to manage ccache + minor fixes

- CMakeLists.txt
- cmake/build_helpers.cmake
- cmake/cmake_uninstall.cmake.in
This PR adds an uninstall target in case users installed ImHex manually with `make install`
From CMake FAQ : https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake
> added `make uninstall`

- plugins/builtin/source/content/views/view_hex_editor.cpp
On some editors, the redo shortcut is mapped to Ctrl+Shift+Z
I think it would be great to support both shortcuts (the other one being Ctrl+Y)
> add Ctrl+Shift+Z shortcut to redo

- lib/libimhex/source/helpers/fs.cpp
Both Windows API and `std::wstring` constructor use wide-char count as size parameter, so the ` * sizeof(TCHAR)` is not needed.
And the size and output content of Windows API include the terminating null character, but C++ string should not. If includes, [magic.cpp#L30](https://github.com/WerWolv/ImHex/blob/bececff9e5a9d1e5f42b3227ea9c2bb1f46c1e83/lib/libimhex/source/helpers/magic.cpp#L30) will concatenate a string like `"path1\0:path2\0:"`, and only the part before `\0` is passed to libmagic when use `.c_str()`.
> fix: Pattern auto-loading issue on Windows

- plugins/builtin/source/content/views/view_hex_editor.cpp
This PR fix the "'Esc" key on the Ctrl+G (goto) ( helps #809 )
It also closes popups directly instead of exiting the input **and then** exiting the popup (it doesn't seem to be possible to do globally per an option in imgui, see https://github.com/ocornut/imgui/issues/2620#issuecomment-501136289)
> Change "Esc" key behavior on hex editor popups

- cmake/build_helpers.cmake
I've been wondering for months why configuring CMake took so long (sometimes 30secs ?), I thought users would like to know what's happening
> Tell users patterns are being downloaded

- plugins/builtin/romfs/tips.json
This will help users to know about this "feature". It's not really documented anywhere else that disabling unicode symbols make ImHex load faster
> Add tip about unicode symbols

- .github/workflows/build.yml
Temporary fix until appimage-builder merges https://github.com/AppImageCrafters/appimage-builder/pull/281 and make a new release
Related issue : https://github.com/AppImageCrafters/appimage-builder/issues/280
> apply patch to appimage-builder for version parsing

- plugins/builtin/source/content/tools_entries.cpp
Wrong labels resulting in missing labels in UI for `View -> Tools -> File Tools -> Splitter`.
> fix: Wrong i18n labels

- plugins/builtin/source/content/global_actions.cpp
- plugins/builtin/source/content/main_menu_items.cpp
This will disable Alt+S when there is no save file set
Bonus commit to not check for a writable provider in order to save, as discussed on discord
> do not check for writable provider to save project

- .github/workflows/build.yml
Two things in one !
First, this PR cleans up the CI file. I mostly remove comments with the rationale that we can also get them back from the older commits
The PR also moves the AppImage build to a different runner than Ubuntu. I made a mistake thinking that AppImage was "just a repackaging of the deb file". Some flags are changing, and this is causing the build to occur twice in the runner.
Ready for merge
> cleanup build CI + separate Ubuntu and AppImage builds

- main/source/window/window.cpp
Repeatedly mashing a key (**not** holding it down) eventually starts to lag.
https://user-images.githubusercontent.com/25270458/212798881-120a792d-c481-4f1d-9138-12c6b6fe689e.mp4
I believe this is because m_hadEvent could be set during glfwWaitEventsTimeout and then immediately cleared before ever being checked. This patch changes the order so that m_hadEvent is preserved until the next check so that the frame rate can be unlocked. This also no longer clears m_hadEvent when the window is invisible or iconified but I'm not sure if that matters.
> fix: Frame rate not unlocking correctly

- plugins/builtin/source/content/views/view_find.cpp
> Fix string search missing end string

- lib/libimhex/include/hex/providers/provider.hpp
- plugins/builtin/romfs/lang/base.json
- plugins/builtin/romfs/lang/en_US.json
- plugins/builtin/source/content/providers/disk_provider.cpp
- plugins/builtin/source/content/views/view_provider_settings.cpp
PR title is self explaining
I may modify other providers implementations to display a detailed error message later
I'm not sure how to deal with other locales because the format changed. Before, I had to add and comment the key in all locale files, now I'm not so sure.
> Display a more detailed error when opening a raw disk provider

- lib/libimhex/include/hex/helpers/fs.hpp
- lib/libimhex/source/helpers/fs.cpp
- main/source/init/tasks.cpp
This pull request changes Config Directories on Linux to only include the XDG_CONFIG_HOME directory, as opposed to all directories in XDG_DATA_DIRS before (introduced in https://github.com/WerWolv/ImHex/pull/644/files#diff-c1a4d2b63fed168a9a3568944e9cadeae096f2ddcec3649e4a9b2d29fd104be0L162-L166).
Reasons:
- This changes the location of the config file to the standard directory meant for configurations
- This prevents the config file from being read/written in system locations, like /usr/share
This PR also includes a migration task that will run on Linux and move config/GUI dimensions to the new directory
as a bonus, as discussed on discord, it writes the logs to a Data directory instead of a Config directory
> Move config file to XDG_CONFIG_HOME

- lib/libimhex/include/hex/api/event.hpp
- plugins/builtin/source/content/views/view_pattern_editor.cpp
Currently there is no way to save the pattern code progamically from a plugin unless the builtin plugin is modified to add those events. This pull request will be adding ability to load and save pattern code from specified file.
> feat: allow loading and saving pattern code via events

- CMakeLists.txt
- cmake/build_helpers.cmake
- main/source/init/tasks.cpp
- plugins/builtin/source/content/settings_entries.cpp
- plugins/builtin/source/content/welcome_screen.cpp
This is aimed at use by linux distros, where package updates come from a central location, and users shouldn't need to worry about updating ImHex on their own. This disables parts of the ImHex UI that would not be useful in that case.
Tested and confirmed that this works in both states of the of the `-DIMHEX_DISABLE_UPDATE_CHECK` switch.
> build: Add option to disable update checking

- plugins/builtin/source/content/views/view_data_processor.cpp
This will correct the errors `cannot use operator[] with a string argument with string[..]` when loading a project
> Explicitely convert data processor project data to json

- lib/libimhex/include/hex/helpers/disassembler.hpp
- plugins/builtin/source/content/views/view_disassembler.cpp
This fixes build on Debian with Capstone from packages.
> build, capstone: Move WASM enum values and related code into the condtional block of API >= 5 (since it was introduced then).

- lib/libimhex/include/hex/helpers/logger.hpp
- lib/libimhex/source/helpers/logger.cpp
- main/source/window/window.cpp
- plugins/builtin/romfs/lang/base.json
- plugins/builtin/romfs/lang/en_US.json
- plugins/builtin/source/content/welcome_screen.cpp
- Add a new file 'crash.json' to store metadata about the crash, like the log file or project opened
- show the log file of the session that caused the crash to the user
- Correctly restore the project path
> Improve crash handling

- .github/workflows/build.yml
Fedora 36 is EOL.
Build roots for it were taken offline this morning so builds against it will fail now.
> remove fedora 36 builds

- main/include/window.hpp
- main/source/window/linux_window.cpp
- main/source/window/macos_window.cpp
- main/source/window/win_window.cpp
- main/source/window/window.cpp
- plugins/builtin/source/content/ui_items.cpp
- plugins/builtin/source/plugin_builtin.cpp
- plugins/windows/source/content/ui_items.cpp
- plugins/windows/source/plugin_windows.cpp
Tested on Linux (non-borderless) and Windows (borderless)
You may want to also test it just to be sure
> Also display titlebar buttons when not running borderless

- plugins/builtin/source/content/views/view_about.cpp
Really small issue, in Help->About->Imhex directories, there would be an extra entry at the end because you seemed to loop over the fs::ImHexPath::END entry
> Do not loop over 'END' ImHexPath

- lib/libimhex/include/hex/api/event.hpp
- lib/libimhex/source/api/project_file_manager.cpp
- plugins/builtin/CMakeLists.txt
- plugins/builtin/include/content/recent.hpp
- plugins/builtin/source/content/recent.cpp
- plugins/builtin/source/content/welcome_screen.cpp
This PR does two things :
- save opened projects as recent entries
- refactor stuff about recent entries in a separate file. The reason is that I felt like welcome_screen.cpp was really big ( 685 lines before this, 500 now). What do you think ?
> save opened projects as recent entries

- plugins/builtin/source/content/recent.cpp
This should fix the current crash when opening a project on Windows
> explicitely convert std::fs::path to std::string

- plugins/builtin/include/ui/hex_editor.hpp
Fixes `error: private field 'm_grayZeroHighlighter' is not used [-Werror,-Wunused-private-field]`
> Remove `m_grayZeroHighlighter` from `hex::plugin::builtin::ui::HexEditor` from `plugins/builtin/include/ui/hex_editor.hpp`

- lib/libimhex/include/hex/api/project_file_manager.hpp
- lib/libimhex/source/api/project_file_manager.cpp
- main/source/crash_handlers.cpp
- plugins/builtin/source/content/project.cpp
This PR fixes some things about crash handling:
- when the terminate handler is called, immediately set it back to the original one, so can't make a recursion if the crash-handling code fails
- Only save projects if the crash occured after Imhex finished startup
- do not update the project location when saving the crash backup file: this will remove problems when `EventAbnormalTermination` is called before `crashCallback()`
I also added a bit more documentation
> reset terminate handler directly when being called + some other crashes to crash handling

- lib/libimhex/include/hex/providers/provider.hpp
- lib/libimhex/source/providers/provider.cpp
- plugins/builtin/include/content/providers/view_provider.hpp
- plugins/builtin/source/content/main_menu_items.cpp
- plugins/builtin/source/content/views/view_hex_editor.cpp
- plugins/windows/include/content/providers/process_memory_provider.hpp
Currently, the providers use the method `isSavable()` to determine both if they can use "Save" or "Save as".
This behaviour is problematic because some providers may need to be saveable but not saveable as: for example the view provider. The original provider may not allow to be saved.
I separate these two behaviour by creating another function: `isDumpable()`, that return true by default but can be overridden by the provider to return false, if the provider should not be dumped in any way.
While I was at it, I also marked "export" operations as needing the "dumpable" flag. That way, we can't accidentally export the whole address space of a process as base64.
I also added documentation for these some functions in Provider
> separate the behaviour of being savable and being dumpable for provider

- lib/libimhex/CMakeLists.txt
- lib/libimhex/include/hex/helpers/utils_linux.hpp
- lib/libimhex/source/helpers/fs.cpp
- lib/libimhex/source/helpers/utils.cpp
- lib/libimhex/source/helpers/utils_linux.cpp
- main/source/window/linux_window.cpp
This PR it just a hack to fix #1160 , it doesn't solve the underlying problem.
It fixes the problem because by using execvp() directly, it avoids the call to `sh` done with `system()`, which has a bug on Ubuntu 22.04 which makes it i,compatibles with the glibc inside the AppImage.
It doesn't fix the underlying problem because the programs we call themselves still link to the AppImage's libraries instead of the system ones.
> Use execvp() instead of system() on Linux 

- main/source/window/window.cpp
As requested on Discord, a PR to revert the FPS limiter back to the one that was used in v1.30.1.
The new FPS limiter seems to be flawed in that it runs at about half the speed it is supposed to be.
See this illustration:
Left is v1.30.1, right is the new version (without this fix). See how long it takes to respectively reach 0xE90.
This is not a performance issue, because when you fully unlock the framerate on the right, it's just as fluent as on the left.
> Reverts the FPS limiter back to the one used in v1.30.1

- plugins/builtin/include/ui/hex_editor.hpp
- plugins/builtin/romfs/lang/de_DE.json
- plugins/builtin/romfs/lang/en_US.json
- plugins/builtin/romfs/lang/es_ES.json
- plugins/builtin/romfs/lang/it_IT.json
- plugins/builtin/romfs/lang/ja_JP.json
- plugins/builtin/romfs/lang/ko_KR.json
- plugins/builtin/romfs/lang/pt_BR.json
- plugins/builtin/romfs/lang/zh_CN.json
- plugins/builtin/romfs/lang/zh_TW.json
- plugins/builtin/source/ui/hex_editor.cpp
Finalization of #1245 by adding a toggle to the hex editor itself, issue can be closed afterwards.
> Added toggle for human-readable units in hex editor footer

- .github/workflows/build.yml
This PR makes the CI go faster (yet again)
- The ArchLinux (and possibly other) jobs cache size was too small (50MiB), and was getting filled up in less than a run (400MiB). I put the cache size to 1GiB eveywhere to make sure it doesn't happen
- This will need monitoring to make sure the cache doesn't fill up with old build caches (ccache has an option for that but I'm not sure how well it works by default)  
- The keys used for the Ubuntu build were the same fot both Ubuntu 22.04 and Ubuntu 23.04, which could cause only one of them to get a good cache
> git: Make CI faster

- lib/libimhex/include/hex/providers/provider.hpp
- plugins/builtin/include/content/providers/memory_file_provider.hpp
- plugins/builtin/source/content/recent.cpp
Memory providers were saved in recent entries, but they do not save any data, so we were essentially saving an empty provider as recent
I added a `isSavableAsRecent()` property to the Provider class to control whether a provider should be saved as recent
> feat: Do not save memory providers as recent entries

- lib/libimhex/include/hex/api/event.hpp
- lib/libimhex/include/hex/providers/provider_data.hpp
- plugins/builtin/source/content/providers/memory_file_provider.cpp
#1238 case B
I added a function to move data in PerProvider members from a provider to another, and use that function when saving a memory provider
> feat: move PerProvider data to new provider when saving memory provider into file provider

- plugins/builtin/source/content/providers/file_provider.cpp
`hex.builtin.provider.file.menu.into_memory` didn't have a the `_lang` suffix, probably got forgotten
> fix: add _lang suffix to "Load into memory" localization string

- dist/rpm/imhex.spec
Fedora rawhide build is currently failing, because its trying to use the system version is llvm, which is llvm 17
This PR makes Fedora packages use our bundled llvm
> git: build llvm ourselves in Fedora packages

- plugins/builtin/source/ui/hex_editor.cpp
Before this setting was moved out of the global settings window, it would persist. This PR restores that, even though it's now part of the Hex Editor itself.
> feat: Remember bytes per row in Hex Editor

- plugins/builtin/include/content/views/view_store.hpp
- plugins/builtin/romfs/lang/en_US.json
- plugins/builtin/source/content/views/view_store.cpp
This PR modifies the content store view to accommodate for the new content the API will send, the pattern description and authors.
For that, I changed the "description" column to be wrapped (because the description might be so long it takes multiple lines) and added a "authors" column
Before
After
> feat: Adapt content store view for new API contents

- main/source/init/splash_window.cpp
Sometimes when debugging, startup tasks don't yield enough info
This PR prints the success status of each task, and a confirmation print that all tasks were executeed
> feat: Add more details to startup tasks

- plugins/builtin/source/content/providers.cpp
When loading providers, the loadSettings() function can throw an error. In this case, we should treat this the same as if it failed to open the provider
Else, the project might entierely fail to load because one provider has thrown an exception
> fix: Handle exceptions thrown by providers on loadSettings()

- lib/libimhex/include/hex/api/event.hpp
- lib/libimhex/source/api/content_registry.cpp
- plugins/builtin/include/content/views/view_pattern_data.hpp
- plugins/builtin/include/ui/pattern_drawer.hpp
- plugins/builtin/source/content/views/view_pattern_data.cpp
- plugins/builtin/source/content/views/view_pattern_editor.cpp
- plugins/builtin/source/ui/pattern_drawer.cpp
As discussed (many times) on Discord, does the same as the new favorite tag, but instead allows you to add multiple groups.
Initially, this would cause some insane issues with draw/reset (apparantly) fighting eachother in the pattern drawer. After a lot of trial and error, I decided to rewrite the flow that is responsible for calling reset. Now evaluating patterns is the one to decide when the reset happens, not the core "game"-loop.
To make sure that draw and reset can never happen at the same time, the mutex originally used for the favorites has been repurposed. Due to the restructuring, the mutex in the favorite-task is no longer needed, as that will only ever kick-off after reset is called and if there are actually patterns, which can never line up to be accessed on different threads …
> Add support for the hex::group attribute and various fixes

- lib/libimhex/include/hex/helpers/disassembler.hpp
This might fix building with capstone 4 as discussed in https://discord.com/channels/789833418631675954/1155669027306340393/1155669027306340393 
moves the max definition inside the if statement that checks for capstone 5
> fix building with capstone < 5

- .github/workflows/build_web.yml
Web deployments currently run on forks when pushing on master, which fails because github pages are not enabled.
This PR disables web deployments on forks
> fix: disable web deployment on forks

- .github/workflows/analysis.yml
- .github/workflows/build.yml
- .github/workflows/build_web.yml
- .github/workflows/tests.yml
Rationale: secrets (and vars) are not shared with pull requests, so they can't use the cache
This PR fix that
> Delete CACHE_VERSION secret from cache keys

- main/gui/source/init/splash_window.cpp
- main/gui/source/window/window.cpp
- resources/dist/macos/Info.plist.in
When starting ImHex on a MacBook model with both integrated and discrete graphics, it will force the computer to use the discrete graphics card. This causes increased power usage, meaning the fans will spin up, the battery will drain faster, etc. This program is not very graphics intensive, so using the discrete graphics card shouldn't be needed.
I changed the [`GLFW_COCOA_GRAPHICS_SWITCHING`](https://www.glfw.org/docs/latest/window_guide.html#window_hints_osx) setting in GLFW to not enforce using the discrete graphics.
My editor is configured to automatically remove trailing whitespace, so I hope that those whitespace changes are ok
> MacOS: Don't force using discrete graphics card

- dist/AppImageBuilder.yml
These libraries were making the AppImage fail on ArchLinux, and they are on https://github.com/AppImageCommunity/pkg2appimage/blob/master/excludelist
> build: Remove some libGL libraries from the AppImage

- dist/Arch/PKGBUILD
Right now imhex from the `imhex-bin` ArchLinux package do not have an icon, because the package do not bundle one
This PR fix that
> build: install pixmaps folder in ArchLinux package (to have the icon)

- lib/libimhex/include/hex/api/event.hpp
- lib/libimhex/source/api/event.cpp
Fixed possible bug of  `EventManager::unsubscribe`
`std::map` only allows unique key, but the same token can subscribe to multiple events.
https://github.com/WerWolv/ImHex/blob/1a2a926b772f32d4f5e4c723c48e0e6e65a16b0a/lib/libimhex/include/hex/api/event.hpp#L104-L107
If the previous token has already subscribed to an event, then when subscribing again, `getTokenStore().insert` will not do anything (Because its type is `std::map`)
https://github.com/WerWolv/ImHex/blob/1a2a926b772f32d4f5e4c723c48e0e6e65a16b0a/lib/libimhex/include/hex/api/event.hpp#L122-L134
At this point in `unsubscribe`, the `iter` may not be able to find the correct event and erase it
Change `tokenStore` to `std::multimap` instead of `std::map`,  which cannot unsubscribe multiple events correctly
> fix `unsubscribe` bug

- main/gui/source/init/splash_window.cpp
- main/gui/source/window/window.cpp
This PR removes the `glfwWindowHint(GLFW_SAMPLES, 1);` line
It is removing the window transparence on Linux
> fix: Re-enable window transparence on Linux

- dist/web/Dockerfile
This PR integrates my libmagic patch into the Dockerfile rather than my vcpkg fork (so we can use the official vcpkg repository in the future)
That said, we still use my vcpkg fork for now because official vcpkg fails to compile freetype
> build: Integrate my libmagic patch into the Dockerfile rather than my vcpkg fork

- dist/web/Dockerfile
https://github.com/microsoft/vcpkg/pull/34157 fixed the issue we had with brotli (freetype) so we can now use the microsoft vcpkg repository, instead of my fork which was frozen at a date before the brotli problem
> build: use microsoft vcpkg repository for the web build

- plugins/builtin/source/content/tools_entries.cpp
Testing various fonts and sizes I realized there were still problems with the layout of the bit labels. Also I reorganized the code so that lambdas are defined just before they are used. Comments needed punctuation too.
Part of the problem was that I had been assuming all along that the check boxes were ImGui's originals which are always square. In actuality the width is determined by the width of the character for '0'. Also ImGui table was adding spacing to separate cells which made the boxes not start at same place as column. Also for some reason using indent of zero didn't work as expected but using 0.1 pixels worked.  With those problems fixed it is fairly easy to make sure the labels are centered at the box except when the first mantissa checkbox gets a label which is wider that the …
> fix: Fixed spacing in bit labels so it works for any font and any size.

- README.md
Just a very simple update to point to the right documentation URI
> fix: Updated wrong link to pattern language docs

- lib/libimhex/source/subcommands/subcommands.cpp
Right now subcommands with more than one arguments fail, because we didn't properly separate the arguments with \0
This PR fixes that
> fix: fix forwarding multiple arguments to subcommands

- plugins/builtin/include/content/views/view_store.hpp
- plugins/builtin/romfs/lang/en_US.json
- plugins/builtin/source/content/views/view_store.cpp
Currently ImHex does not handle well content store entries that are in a read-only folder (typically managed by an external, system-wide package manager)
This PR fix that
> feat: handle content store entries managed by the system (in a read-only folder)

- main/gui/source/init/tasks.cpp
Running this task in a thread not related to the splash screen will allow us to make the request without a very small timeout
> feat: do not make splash screen wait for checkForUpdates task

- .github/workflows/build.yml
Context: MacOS 11 (Big Sur) is EOL + llvm@17 has been released, and it has no binaries for Big Sur, making the CI hang
> Make MacOS builds use MacOS 12 instead of 11

- plugins/builtin/source/content/main_menu_items.cpp
It turned out that the achievement "ROM hacks" wasn't actually unlockable.
I'm not sure if the IPS32 patch also has to trigger this achievement, but it seemed logical to me so I added the call to both methods.
> Unobtainable achievement fix

- plugins/builtin/source/content/hashes.cpp
Before this PR, the CRC-32 value of ImHex is not like most of others.  
Just set m_reflectIn and m_reflectOut of CRC-32 true by default.
> fix: Calculate default CRC-32

- .dockerignore
This only helps locally, to avoid copying local build folders to the build container
> build: Add .dockerignore

- lib/third_party/imgui/include/imgui_impl_opengl3_loader.h
Commit  1249eb326112a8caa518151f0d82fbb7619938c0 added `#include <GL/gl.h>` in a file, but MacOS uses `<OpenGL/gl.h>`.
If compiling on MacOS, use `<OpenGL/gl.h>`. Otherwise, use `<GL/gl.h>`.
There is a redefine, so I used the preprocessor to ignore it for MacOS. This feels a little awkward to me (but I don't know how to do it better).
I'm not particularly familiar with C++, so let me know if this is the right solution. This is also my first pull request, so feel free to roast me for anything else :)
> fix: gl.h for MacOS

- main/gui/source/window/window.cpp
The entry is "hex.builtin.setting.interface.window." but I think it should be "hex.builtin.setting.interface.window.x"
> fix: bad entry in settings ends in .

- .github/workflows/build.yml
Fedora 37 goes EOL in less than a week.
> Add f39 builds, remove f37

- README.md
I saw that diffing is not mentioned anywhere in the README.md and people I referred ImHex to did not consider using the editor due to diffing being a requirement for them.
Diffing is not mentioned anywhere in the README.md
Added Diffing to the features list of README.md
> impr: Include diffing as a feature in README.md

- lib/libimhex/source/api/plugin_manager.cpp
d511080814dc78ad39a63f2071003c07ee37673c introduced a regression where running imhex with arguments (i.e. `imhex blob1.bin blob2.bin`) will segfault due to a null pointer dereference.
This patch updates `getSubCommands` to follow the same control flow as `getFeatures`, where if the function returns a null pointer, it will return gracefully rather than crash.
> fix: segfault when starting with file arguments

- plugins/builtin/source/content/providers/memory_file_provider.cpp
This is in an effort to avoid unnecessary popups
> feat: Do not make memory providers dirty when creating them

- .github/workflows/build.yml
I introduced CMakeCache cache ~a year ago, mainly because curl was doing a bunch of tests that took time. curl is now removed, and this cache seems to add more problems than it solves, e.g:
- builds rely on a previous build configuration, so we can't make sure building from scratch work, and we could inherit flags from previous builds
- Errors like this on MacOS
```
/Users/runner/work/ImHex/ImHex/plugins/script_loader/source/loaders/dotnet/dotnet_loader.cpp:15:10: fatal error: nethost.h: No such file or directory
15 | #include <nethost.h>
|          ^~~~~~~~~~~
```
> feat: separate cmake configure steps + remove CMakeCache cache

- dist/web/Dockerfile
- dist/web/source/wasm-config.js
This PRs adds a new file to the deployed web version: `imhex.wasm.size`
This file is responsible for showing the size of `imhex.wasm`
> fix: Fix detected wasm file size being wrong

- .github/workflows/build.yml
For some reason, makepkg started creating a imhex-bin-debug package along the regular imhex-bin package, which made the build fail
This PR remove it after running makepkg
> fix: Remove debug package created by makepkg

- plugins/decompress/CMakeLists.txt
Prior to this, at least on Linux/MacOS/etc, I guess it was not possible to compile with Zstd included for `hex::dec::zstd_decompress()`:
Every other target lib for the decompression plugin would compile, **except for** Zstd. Additionally, the target name `zstd` caused CMake to not be able to find `Find(ZSTD).cmake` due to case-sensitivity differences between Windows and Unix-based file paths, of course.
With that said, I'm not too sure if this will break building w/ Zstd on Windows... Hopefully not :smile:
> Fix compiling with Zstd (at least on *nix)

- lib/third_party/imgui/custom/include/emscripten_browser_clipboard.h
- lib/third_party/imgui/custom/source/imgui_impl_glfw.cpp
WASM build does not support copy/paste beyond the application. Meaning, there's no practical way of sending text back and forth across the application border.
There are lengthy threads why this is a technical challenge in WASM/Browser world, e.g:
- https://github.com/pthom/hello_imgui/issues/3
- https://github.com/emscripten-core/emscripten/pull/19510
Implements a workaround solution as Header only C++ library, as proposed and implemented at: https://github.com/Armchair-Software/emscripten-browser-clipboard
Maybe there are cleaner ways of achieving the functionality. Definitely would like to have some discussion around this. 👀 
ℹ️ The proposed PR "works for me" on Windows, using CTRL-C/V shortcuts to copy text from and to the application. On MacOS the system shortcut to Paste is different …
> PoC: Support Copy/Paste on WASM build outside the application border

- cmake/modules/FindYara.cmake
Discord discussion: https://discord.com/channels/789833418631675954/789840633414025246/1213564050848485427
> fix: use `find_library()` instead of `find_file()` to find system yara library

- dist/get_deps_tumbleweed.sh
After installing the dependencies, I have managed to successfully compile the project as described in the building instructions:
https://github.com/WerWolv/ImHex/blob/master/dist/compiling/linux.md
I have tested the script on a fresh installations of the OpenSUSE:
- Tumbleweed Server
- Tumbleweed Generic Desktop
Dependencies added in the script are based off of scripts for other Linux distributions.  
Because of that, some download dependencies might not be necessary (or could be already included by other packages), so it is very much possible that some of them could be removed.
> Add dependency download script for OpenSUSE Tumbleweed

- main/gui/source/init/splash_window.cpp
- main/gui/source/window/window.cpp
When running ImHex under Wayland, the window icon is missing.
Setting [```GLFW_WAYLAND_APP_ID```](https://www.glfw.org/docs/latest/group__window.html#gafbf1ce7a4362c75e602a4df9e1bdecd3) to fix the issue.
Before:
After:
> Fix missing window icon under wayland

- main/gui/source/window/win_window.cpp
Implements support for DWM immersive dark mode.  
Closes #1635.
Uses the DwmSetWindowAttribute API to enable this feature.
Documentation can be found [here](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/apply-windows-themes#enable-a-dark-mode-title-bar-for-win32-applications).
Before:
After:
Nothing.
> [Feature] Support DWM immersive dark mode on Windows.

- plugins/builtin/include/content/providers/file_provider.hpp
- plugins/builtin/source/content/providers/file_provider.cpp
This PR aims to address #1645 that caused the built in file provider's change monitor to trigger the notification popup dialog multiple times in a row after multiple external file changes.
I added an additional boolean field `m_changeEventAcknowledgementPending` that tracks whether there are any pending or unacknowledged change notification dialogs to prevent further dialogs from being opened. The flag is only reset to its initial value once the user has acknowledged the first `PopupQuestion` dialog.
Since the file is reloaded only after the user clicks 'Yes', it is unnecessary to ensure that only the latest popup is acknowledged.
> Fix a bug that caused the file provider's monitor to trigger the change dialog multiple times in a row (#1645)

- main/gui/source/window/window.cpp
When the close button is clicked, `ImGui::BeginPopupModal()` sets the bool passed into the second parameter (p_open) to false. However, the closing logic did not take this into account, making it difficult to actually close modal popups.
For example, closing the "Export pattern File" modal took several clicks on the "X" button, now it closes instantly.
I added an additional check for the `open` variable being `false` in the logic that checks the closing condition.
> fix: Not being able to close certain modal popups with the close button on the title bar

- plugins/builtin/source/content/views/view_hex_editor.cpp
- plugins/ui/source/ui/hex_editor.cpp
This PR offers two improvements:
1) When selecting / jumping to an offset that falls within the current viewport of the scroll view, the scroll offset will no longer force the selected byte to the top of the view. Instead, the scroll offset will only be changed if the selected byte is outside the current view.
2) In case a wrong offset is entered into the Select or Goto dialog (e.g. and offset beyond EoF), the dialog's button will be disabled.
For the first change, I modified the logic that recalculates the `m_scrollPosition ` based on the current byte offset.
For the second change, I added validation logic to both popups to ensure that the entered offsets are valid (using `provider->getActualSize()`). In case of the Select popup, I wrapped the button into an `ImGui::Begin/EndDisabled` to …
> Fix jump scroll offset

- plugins/builtin/source/content/views/view_hex_editor.cpp
Merging my previous PRs, #1660 and #1658 has resulted in a conflict causing an application crash due to a missing `ImGui::BeginDisabled();` in the `PopupSelect` class. Specifically, none of the code related to offset validation made it into the final merge. This PR fixes the crash by reintroducing the deleted lines.
The nightly release build seems to be unaffected by the crash, most likely because ImGui's `DisabledStack` assertions are only enforced in Debug mode. The offset validation was still missing before this fix.
> fix: Program crash caused by missing ImGui::BeginDisabled()

- plugins/builtin/romfs/lang/de_DE.json
- plugins/builtin/romfs/lang/en_US.json
- plugins/builtin/romfs/lang/es_ES.json
- plugins/builtin/romfs/lang/it_IT.json
- plugins/builtin/romfs/lang/ja_JP.json
- plugins/builtin/romfs/lang/ko_KR.json
- plugins/builtin/romfs/lang/pt_BR.json
- plugins/builtin/romfs/lang/zh_CN.json
- plugins/builtin/romfs/lang/zh_TW.json
- plugins/builtin/source/content/popups/hex_editor/popup_hex_editor_find.cpp
This PR adds a shortcut link on the Search (Ctrl+F) popup to the more advanced "Find" view that is normally accessible at the `View > Find` menu.
I added a simple `ImGuiExt::IconHyperlink` link to the `draw()` function of the `PopupFind` class to display the hyperlink. Clicking the link will open the Find view, bring it into focus and close the current popup.
Before:
After:
- Localization keys were added to all .json files, but only `en_US` is populated for now.
> impr: Add a link to the "Find" view in the search popup

- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
TextEditor line numbers were still partially rendered despite mShowLineNumbers being set to false
I wrapped the line no. rendering code in `if (mShowLineNumbers) { ... }`.
Before:
After:
> fix: TextEditor line numbers were still partially rendered despite mShowLineNumbers being set to false

- main/gui/source/window/window.cpp
On macOS `glfwSetWindowSizeCallback` is invoked early during window resizing, rendering a frame in that callback leads to wonky results as the new framebuffer is swapped before the OS has the chance to actually resize the window:
https://github.com/WerWolv/ImHex/assets/1068675/46336419-3fc2-4aa1-b16f-68b0c00e3584
Window contents are redrawn only from `glfwSetWindowRefreshCallback` during resizing, fixing the issue:
https://github.com/WerWolv/ImHex/assets/1068675/3acc5d4a-b2a5-42f0-9015-5e7172a027cf
> impr: Stop rubber banding while resizing on macOS

- lib/libimhex/include/hex/helpers/utils_macos.hpp
- lib/libimhex/source/helpers/utils_macos.m
- main/gui/source/window/window.cpp
- plugins/builtin/source/content/window_decoration.cpp
In borderless mode ImHex disables the standard macOS titlebar rendering and input processing. As a result double clicking the titlebar does not trigger the native macOS behavior set in `System Settings -> Desktop & Dock -> Double-click a window's title bar to [Zoom/Minimize/Do nothing]`.
The ImHex window shows up as blank/transparent when de-minimizing it from the dock.
Widgets experience ghost hover inputs from the past position of the cursor during live resizing.
ImGui elements consume input events in the order they are drawn. As a result by "drawing" an `InvisibleButton` over the content area of the titlebar we can catch unprocessed clicks in the titlebar area. Connecting this button's double clicks to the native window is then a trivial endeavour.
The blank windows was caused by the …
> impr: Restore native macOS title bar double click gesture in borderless mode

- .github/workflows/build.yml
See https://discord.com/channels/789833418631675954/789838296376803358/1246523033884299284 and https://github.com/WerWolv/ImHex/pull/1720
The custom repo seems to pull a more recent glibc, that vanilla Ubuntu doesn't have
It also seems like the ICE I initially encountered (see #1720) doesn't show up anymore ?
> fix: Do not use custom repo gcc 13 for Ubuntu because it doesn't run on vanilla Ubuntu

- dist/imhex.desktop
This adds a list of strings which may be used in addition to other metadata to describe the application. This can be useful e.g. to facilitate searching through entries.
Reference: https://webcache.googleusercontent.com/search?q=cache:https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html
(The original site is currently down due to a Gitlab upgrade)
These keywords are used by [Flathub](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#launchable), [KDE Discover](https://discuss.kde.org/t/does-kde-discover-parse-the-desktop-file-for-categories-and-keywords/7041) and [Gnome Software](https://blogs.gnome.org/hughsie/2016/01/07/the-importance-of-keywords-for-the-software-center/).
Add a `Keywords` entry to the .desktop file.
Here's how the …
> Add keywords to .desktop file

- lib/libimhex/source/api/layout_manager.cpp
At least on Windows (I have tested), it fails to save a layout on the non-portable version of ImHex (unless we have an administrator privilege).
The log (after an attempt to save a layout as "sample") will look like:
| Component | Message |
| --------- | ------- |
| `libimhex` | `Failed to save layout 'sample'. No writable path found` |
But the underlying problem is platform-agnostic.  It can be also a problem on other platforms in other ways.
The layout manager incorrectly queried whether the empty path (effectively the current working directory) is writable before saving the layout (not each "layouts" directories it queried earlier).
This is the snippet of the root cause.
```cxx
std::fs::path layoutPath;
for (const auto &path : hex::fs::getDefaultPaths(fs::ImHexPath::Layouts)) {
if …
```
> fix: Wrong query path when saving the layout

- plugins/builtin/source/content/views/view_bookmarks.cpp
When entering for the end value the same value as the start it is not recorgnized as valid region, because end must be strictly greater than begin. Due to the +1 in the Region constructor this is not correct, because the end is included in the range.
After:
> allow one byte ranges edits

- main/gui/include/stacktrace.hpp
- main/gui/source/crash_handlers.cpp
- main/gui/source/stacktrace.cpp
Related to #1768
This pull request introduces changes to enhance the logging functionality in ImHex by displaying the stacktrace implementation used when showing a stack trace. 
- **Stacktrace Implementation Logging**: Modifies `getStackTrace()` in `main/gui/source/stacktrace.cpp` to return a `StackTraceResult` struct, which includes both the stack frames and the name of the stacktrace implementation used (`Windows`, `execinfo`, or `backtrace` depending on the compilation flags). This allows for the identification of the stacktrace implementation in the logs.
- **Crash Handler Update**: Updates `printStackTrace()` in `main/gui/source/crash_handlers.cpp` to log the name of the stacktrace implementation used before printing the stack frames. This ensures that the implementation name is …
> feat: log stacktrace implementation used

- plugins/builtin/source/content/main_menu_items.cpp
Export selection to file would never finish and wouldn't export the last byte.
It was just a simple off by one when using the selection's end address to calculate the remaining data size. Add one to the remaining size calculation.
Fixes https://github.com/WerWolv/ImHex/issues/1733, https://github.com/WerWolv/ImHex/issues/1619 and https://github.com/WerWolv/ImHex/issues/1597.
> Fix off by one in "Export selection to file"

- plugins/fonts/source/font_loader.cpp
WerWolv/ImHex#1814
1. Remove the flag that wrongly tells `ImFontAtlas` that it owns font data, and remove that parameter from the function signature entirely since now it is always `false`.
2. Rename `takeAtlas` to `getAtlas` since it no longer transfers ownership as of b652565b57bd8a9aac2779b09f51f7bac26afca2.
> fix: Crash on exit when using custom font from file

- plugins/builtin/source/content/welcome_screen.cpp
ImHex asks users whether they wish to opt-in to network connections on start (excellent!), then ignores that and tries to connect to the network anyway when the welcome screen loads (less excellent!).
Also don’t connect to the network on the welcome screen if it is supposed to not do that.
> fix: Do not connect to network on startup when setting is disabled

- plugins/visualizers/source/content/pl_visualizers/3d_model.cpp
Because of `s_drawTexture` never being set to true, textures rarely or never drew in the 3D visualizer.
Set `s_drawTexture` to true when correct (valid texture file/object).
> fix: Textures draw correctly in 3D visualizer

- plugins/hashes/source/content/hashes.cpp
Attempting to do an MD5 hash of a large region (e.g. 2 MiB, ``u8 data[0x200000]``) crashes with a segfault.
In ``hex::plugin::hashes::hashProviderRegionWithHashLib()``, ``hashFunction->TransformBytes()`` is called with an offset of 0, because it iterates over ``data`` and not the entire region.
> fix: Segfault when hashing regions spanning multiple MiBs

- .github/workflows/stale_issues.yml
Added stale issues action:
- Runs on cron every 30 days
- Marks issues as stale after 11 months
- Closes issues marked as stale after 1 month
> Add stale issues action

- main/gui/source/window/linux_window.cpp
- main/gui/source/window/macos_window.cpp
- main/gui/source/window/win_window.cpp
Typing `--help` causes ImHex to exit without outputting anything. Diagnostic messages from glib, ASan, other libraries that might have something important to say, etc. are also suppressed.
This effectively reverts 7c1e33dde6e55ef6347f3b10868a42f456c2ae6a, which was partially reverted only on Windows by code that was left commented out in f114239f51ba68c385e3d46721dd9d97ca4a6c21.
Allowing other libraries to print to stderr may make the output ‘ugly’, but lots of things print to stderr that are important for figuring out why something is bugged, like ASan and glib.
> fix: Missing --help output & other diagnostic messages in console

- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
When this feature was implemented the text editor handled all the keyboard input so the blink reset function could be called in one place for all the key presses. Now that shortcuts are done in the shortcut manager we need to reset the blink state inside all the functions that can affect cursor movement. 
Every function that moves the cursor now calls the blink state reset function at the very start. There may be more functions that need this that haven't been merged but git should show merging conflicts so it should be easy to deal with.
> fix: Reset cursor blink on move

- lib/third_party/imgui/ColorTextEditor/include/TextEditor.h
- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
other separate, but closely related fixes are:
- fix: The previous fix also solved the (unreported) bug of being unable to select utf-8 works by double-clicking.
- fix: The move to next/previous word (Ctr-arrow) behaved differently depending on the direction. I made both the move left/right functions share a much simpler algorithm and rewrote the find start/end of word functions share the same code structure.
The code was using the byte index of the match into the utf-8 string to store the match locations, but the code that sets the selection uses the char index into the utf-8 string instead. Another problem was that the search uses the byte index to determine if it needs to find more matches.
Both problems were solved by introducing two functions to switch from coordinates in units of …
> fix: finding utf-8 strings failed to select their location.

- plugins/visualizers/source/content/pl_visualizers.cpp
- plugins/visualizers/source/content/pl_visualizers/image.cpp
Older image format use to store color values in a small lookup table so that the image could simply store an index to the table. The pattern language is not designed to handle this sort of operation which makes this extension necessary to be able to visualize images of this type.
The changes add an optional parameter to the bitmap visualizer which holds the color lookup table. If the image contains values that are outside the range of possible colors then the first color in the map is chosen. The dimensions of the image can be equal to or smaller than rows*columns depending on how the indices to the color map are stored. For example, you can use 4 bit indices which would make the image half the size (in bytes) but that limits the number of colors to 16. To store colors in sizes larger …
> feat: Extended bitmap visualizer to handle indexed colormaps.

- plugins/decompress/source/content/pl_functions.cpp
https://github.com/WerWolv/ImHex/issues/1895
Added code that handles streamed zstd data. It is based around the [official documentation](http://facebook.github.io/zstd/zstd_manual.html) and the [example](https://github.com/facebook/zstd/blob/dev/examples/simple_decompression.c) provided at the main zstd repo.
The loop around the non-streamed version was also removed because I don't think it was doing anything (no `continue`s, `sourceSize` was always being set to 0).
To test, I generated streamed zstd data with this python script:
```py
import io; import pyzstd;
with open("data.zstd", "wb") as f:
pyzstd.compress_stream(io.BytesIO(b'ab' * 100), f)
```
And then I ran this pattern script:
```
import std.mem;
import hex.dec;
u8 data[while(!std::mem::eof())] @ 0x00;
std::mem::Section data_sec = …
```
> impr: Add streaming decompression to zstd_decompress

- lib/libimhex/include/hex/ui/imgui_imhex_extensions.h
- lib/libimhex/source/ui/imgui_imhex_extensions.cpp
- lib/third_party/imgui/ColorTextEditor/include/TextEditor.h
- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
- plugins/builtin/include/content/views/view_pattern_editor.hpp
- plugins/builtin/source/content/views/view_pattern_editor.cpp
Currently when errors are found the entire line where the error occurred is highlighted and one has to look at the error message in order to find where the error is located on the line. With this PR the line will no longer be highlighted and the location of the error will be marked with an red waved line under the error location. Hovering over the text where the error occurred produces an error overlay so if several errors occur on the same line they can all be seen separately.
The definition of error marker was switched to include column and size as well as line and message like before. 
This change required changing the way view pattern editor draws the error markers because the errors themselves don't have size information. 
Also, a new errorHoverBoxes type was defined to help in the …
> Added underwaved text functions.

- plugins/decompress/source/content/pl_functions.cpp
I was unable to use the LZMA de-compressor even though 7zip was able to identify them as LZMA compressed and decompress them without a problem. Under the debugger the `lzma_code()` call was returning `LZMA_MEMLIMIT_ERROR`.
I found online that the error can be fixed using `lzma_memlimit_set()` using a value obtained with `lzma_memusage()`. I tried to avoid having to call `lzma_code()` twice but if the functions are called before the first `lzma_code()`the values of memory obtained fall short and error occurs again.
I suspect that there are better ways to deal with this other than the code proposed in this PR, but I haven't been able to find any.
> fix: the lzma decoder seems to always fail with a memory error

- main/gui/source/window/window.cpp
The bug described  in #1663 was caused by an optimization of the display rendering that uses drawlists to detect changes. The changes in the 3-d visualizer don't contain drawlists when axes are turned off.
The fix is to identify the 3d visualizer among the command lists of the main window and, if found, avoid skipping frames regardless of the result of the comparison of drawlists.
> fix: for issue #1663 (3d visualizer becomes very slow without...)

- plugins/visualizers/source/content/pl_visualizers/3d_model.cpp
changes needed were:
1) add an extra dummy empty widget so that width of child and parent are not always the same. 2) Width of reset button needs to be adjusted when the width of the child is decreased so that the parent is decreased too.
> fix: Unable to resize 3d-visualizer window in x-direction.

- plugins/builtin/include/content/views/view_pattern_editor.hpp
- plugins/builtin/source/content/views/view_pattern_editor.cpp
Currently, the pattern editor does not remember where the cursor is located in each provider. For example, suppose you have 2 providers in your project, and you scrolled down to line 200 in the first pattern to make some changes and remembered that the code you want to insert is in the second provider. Then you switch to the second provider, look for the code and find it in line 235. Switch back to the first one, and you are at the beginning of the file. So you again look for the line to edit paste it to realize that it needs code a few lines before the place you found it. You switch to the second provider, and you are at the top again. This gets annoying very fast.
This PR ensures that, when you return to the pattern in the editor for any of the opened providers, the cursor will still be …
> Added per provider cursor position for the Pattern editor.

- cmake/build_helpers.cmake
For some reason removing this line made the Ubuntu and AppImage packages increase in size significantly (68.2 MB  -> 110 MB for Ubuntu, 97.2 MB -> 138 MB for AppImage)
I didn't get the time to investigate properly why
> fix: re-enable C/C++ languages in CMake

- plugins/builtin/source/content/providers/process_memory_provider.cpp
The process memory provider currently doesn't function correctly on Linux due to incorrect handling of the special procfs file `/proc/<pid>/maps`. I don't know if some of this behavior could vary by distro and/or kernel version, but I've observed the following issues in my Ubuntu 24.04 environment.
- The current code in master calls `file.readString()` which attempts to determine the size of the file by [seeking to the end](https://github.com/WerWolv/libwolv/blob/master/libs/io/source/io/file_unix.cpp#L148). However, procfs files don't have a defined size, so this fails with a return of -1. libwolv [interprets this as the file size and attempts to allocate an enormous buffer](https://github.com/WerWolv/libwolv/blob/master/libs/io/source/io/file.cpp#L30), which results in an exception, so …
> Fix process memory provider on Linux

- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
- plugins/builtin/source/content/views/view_pattern_editor.cpp
Moving error markers to be underwaved created s couple of errors: 
- Markers that were 1 char long and located at the end of the line didn't show on text editor. 
- Markers that had zero length or no stack trace didn't show on text editor.
- The first error was caused by an off by one error in the column index. 
- There was no implementation for errors that had no location or zero length. Now errors with no location will be shown at the beginning of the line where they occur. Errors with zero length will be marked from their location to the end of the line, therefore, errors with no stack trace will be marked from the beginning to the end of the line.
> fix: Missing runtime error markers

- plugins/builtin/source/content/providers/process_memory_provider.cpp
Fixes https://github.com/WerWolv/ImHex/issues/1807
Build fails for MacOS x86-64 due to using a wrong architecture header.
Used the headers for mach that auto select the correct architecture.
This is being used in https://github.com/NixOS/nixpkgs/pull/330303 as a patch
> use machine headers to auto select on arch

- lib/third_party/imgui/ColorTextEditor/include/TextEditor.h
- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
- plugins/builtin/include/content/views/view_pattern_editor.hpp
- plugins/builtin/source/content/views/view_pattern_editor.cpp
Fixes provided for the following unreported bugs.
- Environment variables are set to be per provider but used as if they are not. When a project is loaded all the environment variables for each provider are assigned to the first provider making it impossible to add new ones to the other providers.
- When switching providers, the text editor selection, the text editor breakpoints, the console text, the console selection and the console cursor position of the old provider are being assigned to the new provider
This PR aims at fixing both errors by:
- using variable defined to be per provider so that they affect their provider only when necessary.
- creating new per provider variables and using them so that each provider has their own console, selections and breakpoints.
In order to support …
> fix: Per provider fixes.

- plugins/builtin/source/content/views/view_pattern_editor.cpp
fix: pressing F5 (start pattern execution ) while being in a break point hangs ImHex.
The reason for hanging ImHex was that the shortcut procedure was not checking if the pattern was already running, and it attempted to start another one. This makes ImHex wait indefinitely for a lock to be released
To fix the hanging of ImHex we check the runtime for current evaluation and if detected we stop it. In all cases the evaluation is started again.
> fix: ImHex hangs when pressing F5 while in a breakpoint

- plugins/script_loader/source/plugin_script_loader.cpp
std::forward ensures that the arguments are perfectly forwarded to loadScript
By reserving space in the features vector based on the size of scripts, we can avoid multiple memory allocations during the loop. If an exception occurs, returning an empty vector immediately clarifies that no scripts were loaded. Without reservation, each call to emplace_back could potentially trigger a reallocation if the current capacity is exceeded, which is costly in terms of performance. This leads to more efficient memory management and can significantly speed up the execution time when dealing with a large number of scripts.
> reserve space to avoid multiple allocations

- plugins/builtin/source/content/views/view_pattern_editor.cpp
regardless of the method used to pause the evaluation at that line.
> fix: Added code so that when debugger pauses at a line, the line is highlighted 

- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
- plugins/builtin/include/content/views/view_pattern_editor.hpp
- plugins/builtin/source/content/views/view_pattern_editor.cpp
This code fixes issue #1950 This PR depends on PR [#27 ](https://github.com/WerWolv/libwolv/pull/27) on libwolv repo
See description of the problem on the issue linked above
The code in the PR uses function added to the libwolv repository to remove tabs if they exist on the provider. Additionally, any pasted tab on the pattern editor will be translated to spaces automatically. This code was tested successfully using the pattern posted in the issue.
> fix: fixes for issue #1950. 

- lib/libimhex/include/hex/api/achievement_manager.hpp
- lib/libimhex/source/api/achievement_manager.cpp
Loading a file on the command line or using the context menu in windows was triggering an achievement before the achievements file was loaded. This resulted on the achievements.json file to be overwritten with all the achievements reset except for the one to open files.
This PR fixes the problem by introducing a boolean that is used to check if the file has been loaded.
> fix: fixes for issue #1704.

- lib/third_party/imgui/ColorTextEditor/include/TextEditor.h
- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
- plugins/builtin/include/content/views/view_pattern_editor.hpp
- plugins/builtin/source/content/views/view_pattern_editor.cpp
WARNING: this PR won't compile unless [PR 132 from pattern language repository](https://github.com/WerWolv/PatternLanguage/pull/132)  is merged first. Some changes here are shared by at least another PR to this repository but there should not be any conflicts as the shared changes are identical.
fix: Editing patterns with breakpoints sets behaves unexpectedly. As a simple example, set a breakpoint and insert a blank line somewhere before the breakpoint location. The breakpoint will appear to move but in reality it hasn't. To see this set another breakpoint elsewhere in the file and the old one will be displayed where it is really located at.
The reason for this and many other problems with breakpoints is that currently ImHex keeps two set of breakpoints in text editor and in evaluator …
> Fixes for breakpoints

- lib/third_party/imgui/ColorTextEditor/include/TextEditor.h
- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
to avoid potential problems in the future if opening  several popup windows at the same time becomes possible.
> Turned static variables into member variable 

- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
Even if focus is given to the pattern editor the cursor will not show until the editor contains printable chars.
I was using the wrong condition to enter the loop that skipped the default empty document.
The fix was to check if there are lines of text that need to be processed even if they are empty.
> fix: empty documents have no cursor.

- plugins/visualizers/source/content/pl_visualizers/sound.cpp
Fixes [https://github.com/WerWolv/ImHex/security/code-scanning/223](https://github.com/WerWolv/ImHex/security/code-scanning/223)
To fix the problem, we need to ensure that the multiplication is performed using a larger integer type to avoid overflow. This can be achieved by casting one of the operands to `u64` before performing the multiplication. This way, the multiplication will be done in the larger type, preventing overflow.
We will modify the line `index += frameCount * device->playback.channels;` to cast `frameCount` to `u64` before the multiplication.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Fix code scanning alert no. 223: Multiplication result converted to larger type

- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
All asserts in TextEditor.cpp were replaced with IM_ASSERTs so that if they are hit ImHex won't crash and give a nice popup message instead.
> Replaced asserts from TextEditor.cpp

- cmake/build_helpers.cmake
- dist/Arch/PKGBUILD
- dist/imhex.desktop
- dist/imhex.mime.xml
- dist/rpm/imhex.spec
This PR addresses issue #491 regarding the inability to open ImHex project files (`.hexproj`) directly from various UNIX Desktop Environments.
_NB: This PR's scope is limited to UNIX systems, as I have no access to MacOS systems and could not find a way to automatically create file associations on Windows._
In order for project files to be recognised as such, we need to create a new MIME type. According to [RFC 6838 section 3.2](https://www.rfc-editor.org/rfc/rfc6838#section-3.2), additional application MIME types should be defined with a vendor prefix.
_NB: This is preferred over the deprecated `x-` prefix, although RFC 6838 states that the vendor should be "a well known producer"_
This PR proposes a new mime type for ImHex project files: `application/vnd.imhex.proj`, and associates it …
> Implement MIME type support on UNIX systems

- plugins/builtin/source/content/data_visualizers.cpp
At the moment, attempting to edit files using HexII data visualization is impossible as the editing fields only allow numeric characters but is interpreted as a hex value
I yoinked the params used for the hex visualization edit field. 
Ideally this should instead accept the format used by HexII, but I have what scientists describe as a skill issue and this at least makes it possible to use HexII without switching back to hex for editing.
> fix: HexII visualisation does not allow hex characters in the edit field

- lib/libimhex/include/hex/helpers/crypto.hpp
- lib/libimhex/source/data_processor/node.cpp
- lib/libimhex/source/helpers/crypto.cpp
- plugins/builtin/source/content/data_processor_nodes/decode_nodes.cpp
Fix the AES ECB mode in the data processor along with some other misc fixes:
- Fixed nullpointer node not working
- Fixed crypto module incorrectly using mbedtls api
- Fixed crypto module ignoring mbedtls errors
- Fixed silently ignoring of errors in AES node
> Fix AES ECB mode in Data processor

- plugins/disassembler/include/content/views/view_disassembler.hpp
- plugins/disassembler/romfs/lang/de_DE.json
- plugins/disassembler/romfs/lang/en_US.json
- plugins/disassembler/source/content/views/view_disassembler.cpp
This PR implements the feature request #1781, that suggests adding a button to export disassembled instructions into an ASM file.
This adds a button to export the current disassembled instructions to an ASM file. Said file is suffixed by an `.asm` extension if not specified at file creation.
*Note: the file is written to for every `Disassembly` item in the vector, as it was the easiest and most memory-conservative way of doing it.*
The file creation task is implemented based on IPS patch exports, so it fits the same pattern.
A `ToastError` is raised when the ASM export could not complete successfully.
Translations have been implemented for both `en_US` and `de_DE` for the two new keys:
- `hex.disassembler.view.disassembler.export`: file export button
- …
> Export disassembler results to ASM file

- lib/libimhex/include/hex/api/event_manager.hpp
- lib/libimhex/include/hex/helpers/patches.hpp
- plugins/builtin/source/content/achievements.cpp
- plugins/builtin/source/content/main_menu_items.cpp
As described in #1846:
- the `Edit the Hex` achievement doesn't unlock when it should
- the `ROM Hacks` achievement is not using event-driven architecture (the functions call `unlockAchievement` themselves)
Firstly, for the `Edit the Hex` achievement:
- replaced the old event listener on `EventPatchCreated` with a listener on `EventProviderDataModified`, which picks up bytes changes
- ensured the provider data change comes from a File provider, else unlocking the achievement wouldn't make sense
- *Note*: a discovered side effect is that the "Fill" function modifies the provider byte per byte (with a for loop)
- there is no use in testing the size of the data change, as it is always 1 byte
- the Fill function could probably be reworked to fill in whole regions at a time?
About the `ROM …
> Various achievements fixes (Edit the Hex, ROM Hacks)

- lib/third_party/imgui/ColorTextEditor/include/TextEditor.h
- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
- plugins/builtin/source/content/views/view_pattern_editor.cpp
Errors printed in the console can be clicked to have the cursor jump to the source code line where the error is at. 
The mouse cursor changes its shape to indicate which parts of the error message can be clicked on the console. When the cursor jumps, the text editor takes the focus away from the console and it scrolls the window to make the line with the error is visible if it isn't. This code uses the function created for the go-to PR but adds code to switch focus to the target. When the codes are merged please keep both the part that jumps the cursor and the part that sets the focus.
> Feat: Added clickable links to error messages.

- plugins/builtin/romfs/lang/en_US.json
- plugins/builtin/source/content/views/view_hex_editor.cpp
As suggested in #1904, ImHex could benefit from having the capability of pasting text directly into the editor.
This also complements the "Copy as... ASCII string" capability already implemented in the software.
A new shortcut called `Paste all as string` (to resemble the naming of the `ASCII string` copy option) now allows to paste plaintext directly.
This shortcut is mapped to the `CTRL + ALT + SHIFT + V` keybind.
Internally, a new flag called `asPlainText` has been added to the `pasteBytes` function, to minimise code changes and streamline code readability.
The buffer is a simple type cast of the clipboard, without any modification applied, which is then handed to the provider's `write` function.
The new shortcut is visible in the menu, just below the other paste options:
> Add capability to paste as string literal in files

- plugins/script_loader/romfs/lang/zh_CN.json
As described in issue #1841, there was a duplicate on the `Chinese (Simplified)` translation.
After closer inspection, this came from an i18n file (Script loader, specifically) having a bad ISO code (`zh_CN` instead of the expected `zh-CN`).
This also caused a big impact on end users, as loading the latter (`zh_CN`) would cause the whole UI to be displayed in English (the fallback language), and only the script loader being translated into Chinese.
Fixed the i18n code in the Script loader file.
Closes issue #1841
> Fix doubled Chinese (Simplified) translation

- lib/third_party/imgui/ColorTextEditor/CMakeLists.txt
- lib/third_party/imgui/ColorTextEditor/include/TextEditor.h
- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
- plugins/builtin/include/content/views/view_pattern_editor.hpp
- plugins/builtin/source/content/views/view_pattern_editor.cpp
This time it may be for good. 
As requested I added the preprocessing functionality into the pattern editor. I had to duplicate a few functions and update the c++ library to version 20. but now I can make sure the pattern editor doesn't see a tab again. I also removed the preprocessor from where it was before because it is not needed anymore. The changes were tested using a file that used tabs for all its white space. The file was pasted into the pattern editor and imported as well. I both cases no crashes occurred and the files had no tabs on them.
> fix: more tabs to deal with.

- lib/third_party/imgui/ColorTextEditor/include/TextEditor.h
- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
I have implemented a fix that makes the scrollbars behave like they do in VScode. Vertically you can scroll past the end of the file until only the last line can be seen at the top. The horizontal bar behaves as if every line was the same length which is the length of the longest line in the file. Not only this creates a better user experience, but it also fixes the annoying flicker that occurs when scrolling through large files. Also, I have switched all the old draw calls to render text to regular TextUnformatted calls which adds extra stability to the resulting display.
To implement the behavior I added a dummy widget with the desired dimensions.
> improv: VScode like scrolling

- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
The reason for the error were the text preprocessor added to deal with tabs was created to process entire files, not just lines or words. In that context it cleaned trailing new lines if any existed but in the new role that's not only unwanted but erroneous.
After that was fixed the console started to add two empty lines between each output line. When splitting a string using new lines you need to not add a new line to the last line created. Even if the text ends in an end line, the split screen code is set to not discard empty lines.
The fixes are straightforward.
> fix: console either printed no newlines or printed extra ones.

- lib/third_party/imgui/ColorTextEditor/include/TextEditor.h
- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
The top margin changes when popups block some portion on the screen. Previously it was implemented adding blank lines at the bottom which created problems if the windows was scrolled all the way to the bottom and the popups were issued. The newer implementation doesn't use spaces and simply resets the top of the window to be higher making the popup interaction with the window more natural (no text disappears on the lines the popup overlaps the text). changes can be identified form the variables mTopMargin,mOldTopMargin and mNewTopMargin.
Unfortunately those changes revealed problems in cursor navigation that needed to be addressed. Namely, the window will scroll up and down on the line before last/second line at the top and similar problems for the left and right. Those changes correspond …
> Better top margin handling.

- lib/third_party/imgui/ColorTextEditor/include/TextEditor.h
- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
- plugins/builtin/source/content/views/view_pattern_editor.cpp
Two major improvements:
1) see through scrollbars when not hovered.
2) un-scrollable line numbers.
Also enlarged display region by eliminating padding. There is still a problem with lines jumping when the scrollbar is dragged but it is limited to one line and probably due to floating point error for scroll bar number. It is much less noticeable than the previous jumping which could involve several pages.
> Improved scrolling

- lib/third_party/imgui/ColorTextEditor/include/TextEditor.h
- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
- plugins/builtin/romfs/lang/en_US.json
- plugins/builtin/source/content/views/view_pattern_editor.cpp
Some issues related to the padding added to scroll past the end for console that has padding added. 
Added a shortcut to scroll editors one pixel at a time.
Fixed whole lines always drawn at the top even if scroll value is chosen so that only a portion of the top line is visible. This caused errors in horizontal scrolling. 
Fixed Ctrl-F Ctrl-G and Ctrl-H messing the editor display. 
Fixed the end of the line could not be clicked with mouse 
Fixed line numbers and their lines could be displayed at different heights. 
Made numbers that represented lines floats instead of integers to allow partial line display.
> fix: console scroll jumping.

- plugins/decompress/source/content/pl_functions.cpp
See #2033 (`hex::dec::lzma_decompress` reports an error when decompressing a small buffer).
Set the LZMA decompressor memory limit to 1GiB fixed. Print a warning when exceeded, and abort with returning `false`.
Normal result when decompressing a small buffer
Warning message when `memlimit` is exceeded: (Set to 64B here for a demo)
> W: lzma_decompress memory usage 1114168 bytes would exceed the limit (64 bytes), aborting
Is the warning wording OK? I'm not a native English speaker so please change it if you want to.
> fix: Set LZMA decompressor memory limit to 1GiB fixed

- lib/third_party/imgui/ColorTextEditor/include/TextEditor.h
- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
After successfully finding matches and setting the cursor to them, the screen would jump to the original window location upon closing the window.
The error was caused by the wrong assumption that the scroll location should be restored when window is closed. Instead, the right amount of scrolling needs to be calculated to account for the window no longer covering part of the text editor. Unused variable was discarded.
Another unrelated error is that the history of search names cannot be accessed which will be addressed at a later PR.
> fix: find jumps to wrong location.

- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
- plugins/builtin/source/content/views/view_pattern_editor.cpp
The previous implementation seems to have been broken by Imgui updates. 
There is also some improvement in focus handling and also a bug in replace where the last match was not being replaced has been fixed. 
Fixed also slowdown in large files when only one char was typed by not searching until enter has been pressed. 
Added key repetitions for enter and arrows to be able to handle large number of matches and fixed some formatting problems.
> fix: find-replace history

- plugins/builtin/include/content/views/view_pattern_editor.hpp
- plugins/builtin/source/content/views/view_pattern_editor.cpp
Fixes issue #2084 
Error in text editor prevented using shortcuts when language other than English was chosen. 
The code was mistakenly using localized name to test which window had focus a execute the shortcut. 
Fixed it by switching the name of the child window to the constant value used to check the windows focused identity.
> fix: fixes for issue #2084

- main/gui/source/window/window.cpp
- plugins/ui/include/banners/banner_button.hpp
- plugins/ui/include/banners/banner_icon.hpp
The banner windows did not scale with the fonts resulting in cropped text when font size was made bigger than normal.
fixed by ensuring the window is big enough and then making sure text is centered in the y-axis.
> fix: Banner window scaling

- cmake/build_helpers.cmake
- cmake/modules/ImHexPlugin.cmake
Partially fixes #2068 .
This assumes the headers are in "include" for all plugins - this is necessary since the INCLUDES argument of add_imhex_plugin may contain paths to third party libs, whose headers should not be copied. 
To fix this I think it is necessary to add a second argument like "PRIVATE_INCLUDES", which is included, but not installed.
With this it possible to append the ui plugin for example:
```
INCLUDES
$ENV{IMHEX_SDK_PATH}/lib/plugins/ui/
```
and to link against it:
```    
LIBRARIES
/usr/local/lib/imhex/plugins/ui.hexpluglib
```
In a follow-up in the CMake Template for plugins imho there should be fixed, that:
- you can include plugin includes relative to the SDK Path
- you can link plugins relative to the lib path + without the hexpluglib or hexplug extension
> Draft: install include folders of plugins to sdk

- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
The old home shortcut moved the cursor to column zero of the current line. 
Most editors move cursor to the first non-space character instead.
> improv: better home shortcut for pattern editor

- cmake/build_helpers.cmake
'Boost::regex' could not be found unless regex is specified explicitly on some systems.
cf. https://github.com/AOSC-Dev/aosc-os-abbs/pull/9798
cc. @chenx97
> Target "libimhex" links to: Boost::regex but the target was not found.
when building ImHex with system Boost.
Add `COMPONENETS regex` to require regex library explicitly.
> build: Find regex component of Boost explicitly

- plugins/builtin/source/content/views/view_pattern_editor.cpp
This change is to fix a bug reported in discord by berkus and Naheulf about the console missing output lines. The bug was caused by using SetText which replaces the existing text with the text in the argument.
To fix it use InsertText which puts the text at the current cursor position that was already set to the end of the current contents.
Code was tested with pattern used to reproduce the bug and seemed to work when evaluated repeatedly.
> fix: Console editor missed printed output.

- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
A user complained that they imported a file by accident when they meant to export it and as a result had trouble recovering the changes they were trying to save. Auto-save saved the day but there is no reason for not being able to undo changes after importing a pattern.
In fact, the previous implementation treated importing a pattern as a reset on the editor instance which actually erased all previous undo entries. Importing now is treated as a normal editing operation where the entire file is replaced with the imported pattern.
Since all imports use AddText it was easy to add an undo entry to that function while removing the part where the previous undo records were being deleted. 
Care is taken to add the preprocessed version of the imported file to the undo buffer so that unwanted …
> feat: made undo work when importing pattern.

- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
Now that line numbers are not part of the line of code clicking them makes the text editor lose focus. This PR changes that by allowing the user to toggle breakpoints by clicking the field where the line number is located.
Not only will the text editor retain focus when breakpoints are set, but if other parts of ImHex had focus, then it will be transferred to the text editor's current cursor position when the line number field is clicked.
It is also possible to keep the focus where it was and only retain the focus if the text editor was focused when the break point is set. The change is very trivial so if that is preferred I can easily switch it.
> feat: set breakpoint clion style.

- lib/libimhex/source/api/layout_manager.cpp
Saving a layout using the "Workspace -> Layout -> Save Layout ..." button saved to the last writable path in the list that can be found in the "Help -> About" menu. Instead, it should write to the first working path encountered.
Getting all of the writable paths, then picking the first one.
> fix: Saving layout now picks the first path in the list

- lib/third_party/imgui/ColorTextEditor/include/TextEditor.h
- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
The function SetSelection() in the text editor is used as its name implies to set the part of text that will be shown highlighted as a selection. It has two parameter for the selection start and end. Strangely it also uses a third argument to choose one of 3 selection modes namely line, word and normal. This is strange because it seems that if one wanted to select a line one would simply choose the line start and end as the selection values. As evidence of its strangeness it creates a bug when the word end is selected twice and another when SetSelection is used to set the cursor when the window acquires focus breaking selections in the console.
This PR simply eliminates the extraneous argument to SetSelection() ensuring that any problems related to it are fixed once and for all.
> improv: code clarity and fixed console selections.

- plugins/builtin/source/content/views/view_pattern_editor.cpp
When ImHex is built in such a way that the std has asserts activated, the program crashes if the pattern editor is too short. This is the crash log: [imhex.log](https://github.com/user-attachments/files/19954966/imhex.log). As you can see, an assert is triggered in a call to `std::clamp`.
I'm almost sure the crash is caused by the call to `std::clamp` in `ViewPatternEditor::drawContent()`: if `textEditorSize.y`
is less than `400.0F` the min value is greater than the max value, which is undefined behavior. I changed the code so that `200.0F` is used as a fallback when that is the case.
I didn't build and test the change locally because at the moment I don't have the time.
> fix: prevent crash by using a fallback value with bad std::clamp arguments.

- .github/workflows/build.yml
Found post on s.o. about c++ headers not being found when using llvm clang installed using homebrew [here](https://stackoverflow.com/questions/77250743/mac-xcode-g-cannot-compile-even-a-basic-c-program-issues-with-standard-libr) and when I tested the proposed solution in my imhex fork the macos x86 builds were able to complete.
> fix: macos builds

- plugins/builtin/source/content/views/view_pattern_editor.cpp
This was caused by the variable that holds the bar location not being updated when window was resized.
The bar can be moved until only one line is shown in the smaller window. When ImJex window is resized, the proportion of editor/console height is maintained.
> fix: The bar between pattern editor and console could be locked even if it seemed like it should be movable.

- main/gui/source/window/window.cpp
msvc build failing because of a warning treated as an error for variables being used without initializing even though they are being loaded as references.
> build: msvc uninitialized variables.

- plugins/visualizers/romfs/lang/en_US.json
- plugins/visualizers/source/content/pl_visualizers/3d_model.cpp
If you tried to collect the indices using addressof like stl pattern collects vertices you get a small square for visualizer and no error message. The changes here are able to extract the indices if they can be extracted and give an error message if they can't.
> fix: unable to display models if indices are not contiguous in the input file

- lib/third_party/imgui/ColorTextEditor/include/TextEditor.h
- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
- plugins/builtin/include/content/views/view_pattern_editor.hpp
- plugins/builtin/source/content/views/view_pattern_editor.cpp
The recent changes to the text editor to fix the longest line length problems broke the console horizontal scrollbar. The code that displays the console editor was more complicated that it needed be, and it had the bad side effect of resetting the cursor which prevented horizontal scrolling. Adding a function that appends lines to the text editor fixes all problems and makes the code clearer. To accommodate for strings containing zeros, the  code that inserts text was changed to print a '.' when zeros are encountered thus keeping the line length the same.
> fix: horizontal scrollbar missing in console

- lib/third_party/imgui/ColorTextEditor/include/TextEditor.h
- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
- plugins/builtin/include/content/views/view_pattern_editor.hpp
- plugins/builtin/source/content/views/view_pattern_editor.cpp
The recent update that made importing patterns undoable had the side effect of undoing tab changes as well. When working on a fix for that it became clear that the undo/redo stacks were being shared by all providers so that you could undo changes done in a separate file. The problem was fixed by making the text editors (and the console editors as well) to be per provider which gives better control on things like breakpoints and selections and a more robust focusing system that preserves the cursor positions and removes the need to click on a pattern to start editing. There are a lot of changes, but they are mostly all the uses of text editors being now coded differently to manage the providers. File imports are still undoable, but switching providers is not.
> improv: made the text editors to be per provider.

- plugins/builtin/source/content/views/view_pattern_editor.cpp
While working with the section view, I noticed the window wasn't resizable.
This simply removes the `ImGuiWindowFlags_NoResize` flag, and then when drawing the section window sets the hex editor to 70% of the available window, leaving 30% to the pattern data. This is not ideal, but I think before a full rewrite of the section window system this would probably be a simple change to make it a lot more usable.
> Allow Section window resizing

- plugins/disassembler/include/content/helpers/disassembler.hpp
- plugins/disassembler/source/content/pl_builtin_types.cpp
Following the documentation (which is not being updated for this type) on using  `hex::type::Instruction` fails to produce any patterns regardless of how you format the string that is passed to capstone to select architecture and options. 
The error is traced back to mishandling the input string so that the correct parts are not selected properly. Rather than manually selecting the parts of the input string from the result of find it is much simpler to use splitString() (which uses find internally) and does all the work for us with fewer chances for errors.
There are still problems. The resulting string for the  formatter doesn't return the disassembled instruction and prints the variable name with the @ used to place it. To view the instruction you need to unseal the pattern and open the …
> fix: fixes for pattern language dissassembler support

- .github/workflows/build.yml
- cmake/build_helpers.cmake
- dist/rpm/imhex.spec
Gets RPM builds back in sync with Fedora/EPEL and changes to mock instead of fedpkg (slight efficiency improvement since fedpkg is a wrapper around mock).
> Update rpm ci

- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
- plugins/builtin/source/content/views/view_pattern_editor.cpp
With only one menu entry and having set it to use the text editor then the console losses that functionality. Since both the console and the text editor are on the same view, it follows that they must share the menu entries. In some cases it is necessary to determine which of the two editors needs to be processed inside the menu entry itself.
Also an error that caused the creation of invalid coordinates when console is still empty was fixed by setting coordinates to 0,0 for empty files. Another problem was that left clicking on the console didn't select the word under the cursor but it does when left clicking on the text editor. Now it works in both.
The menu entries on the console were removed completely and swapped with a call to obtain the default 'edit' menu for the context popup. …
> fix: find next and find previous not working on console.

- .gitmodules
The current edlib submodule references a commit that's not present in <https://github.com/blawrence-ont/edlib>. This throws off submodule initialization and makes building an ImHex Flatpak using upstream Git HEAD require some nasty Git bodges.
Switching to <https://github.com/Martinsos/edlib> in `.gitmodules` is all that is necessary, since <https://github.com/Martinsos/edlib/commit/0ddc23ea06abd95ab6227442acb4c27bd7607b68> properly exists.
_This section was intentionally left blank._
For those curious, I'm currently working around this by manually appending
```gitconfig
[url "https://github.com/Martinsos/edlib"]
insteadOf = "https://github.com/blawrence-ont/edlib"
```
to `${flatpak_builder_state}/git/https_github.com_blawrence-ont_edlib/config` after `flatpak-builder` has cloned the …
> build: Move back to upstream edlib

- plugins/builtin/source/content/views/view_pattern_editor.cpp
The problem was that the console was calling select word under cursor when no selection was done. Fixed by removing the call.
> fix: console selects word on click.

- plugins/ui/source/ui/hex_editor.cpp
I noticed that an earlier fix was missing parenthesis, so I checked a file of a big size and used a segment size of 1 and only 3 digits were being displayed in spite of needing 6.
> fix: segment numbers are still being cutoff.

- plugins/builtin/source/content/views/view_pattern_editor.cpp
Problem was that a recent commit allowed any subview window to become the current subview with focus which also included the context menu popup. The fix is to list all the subviews that can acquire focus so that they are the only ones that will be detected by the menu condition.
> fix: Menu items greyed out when they shouldn't

- plugins/builtin/source/content/text_highlighting/pattern_language.cpp
The error was caused when the search for the closing delimiter extended past the last token in the sequence, which happened because the initial increments before the loop starts were not being accounted for in the loop ending condition. This was fixed by decrementing the limit of possible steps to account for the initial steps taken.
> fix: typing `t<` on pattern editor spams the log infinitely

- lib/third_party/imgui/ColorTextEditor/include/TextEditor.h
- lib/third_party/imgui/ColorTextEditor/source/TextEditor.cpp
- plugins/builtin/include/content/views/view_pattern_editor.hpp
- plugins/builtin/source/content/text_highlighting/pattern_language.cpp
- plugins/builtin/source/content/themes.cpp
- plugins/builtin/source/content/tools/demangler.cpp
- plugins/builtin/source/content/views/view_pattern_editor.cpp
- plugins/ui/source/ui/pattern_drawer.cpp
Also fixes two bugs:
1) error messages not staying visible
2) uncaught exception when struct name is duplicated.
A lot of the code using coordinates for start and end has been moved to use Selections instead. Created more string manipulation code that uses utf8 indices aka Coordinates directly. This makes implementing editing functions easier by not having to go back and forth from string indices to char indices and back. Currently, the substring, erase and [] operator support coordinates and str indices.
> improv: refactor text editor to follow imhex style.

- main/gui/source/init/splash_window.cpp
With an initial Window size of 1 by 1, the program aborts during launch on my Debian 12 (bookworm) system running the Mate Desktop environment on X11.
The exception from X is the following:
```
$ ./imhex
[18:36:33] [INFO]  [main | Main]                Welcome to ImHex 1.38.0.WIP!
[18:36:33] [INFO]  [main | Main]                Compiled using commit master@59c6d30
[18:36:33] [INFO]  [main | Main]                Running on Linux 6.1.0-37-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.140-1 (2025-05-22) (x86_64)
[18:36:33] [INFO]  [main | Main]                Linux distribution: Debian GNU/Linux 12 (bookworm). Version: 12
X Error of failed request:  BadWindow (invalid Window parameter)
Major opcode of failed request:  18 (X_ChangeProperty)
Resource id in failed request:  0x5400009
Serial number of …
```
> fix: Initialise splash window with correct size

- lib/trace/source/stacktrace.cpp
`std::stacktrace` backend in `hex::trace` does not show frames for external libraries.
If `dlfcn.h` is available, use `dladdr` to retrieve external symbol information.
Before:
```
[02:33:46] [FATAL] [main | Main]               Printing stacktrace using implementation 'std::stacktrace'
[02:33:46] [FATAL] [main | Main]                 (/home/mochaa/ghq/github.com/WerWolv/ImHex/lib/trace/source/stacktrace.cpp:34) | hex::trace::getStackTrace()
[02:33:46] [FATAL] [main | Main]                 (/home/mochaa/ghq/github.com/WerWolv/ImHex/main/gui/source/crash_handlers.cpp:75) | printStackTrace
[02:33:46] [FATAL] [main | Main]                 (/home/mochaa/ghq/github.com/WerWolv/ImHex/main/gui/source/crash_handlers.cpp:125) | hex::crash::handleCrash(std::__cxx11::basic_string<char, …
```
> impr: show external frames when using std::stacktrace backend

- plugins/builtin/include/content/text_highlighting/pattern_language.hpp
- plugins/builtin/source/content/views/view_pattern_editor.cpp
If you project has two patterns and one is very big, switching providers while the big file is being highlighted makes the small one skip its own coloring. The error was caused by a failure to interrupt the ongoing lengthy highlighting process in a timely manner. It appears that calling task interrupt allows the task to run to completion and when the task runs to completion then the retrying mechanism is not trigger and the small pattern never has a task assigned for coloring.
This was fixed by creating a variable that signals the intention to interrupt the current highlighting process. The most used function in the highlighter (used to update the current token) checks the variable and throws an out of range exception causing the interruption of the current highlighter and triggering the …
> fix: Highlighter can fail to update a files contents.

- plugins/builtin/source/content/views/view_pattern_editor.cpp
- plugins/ui/include/ui/text_editor.hpp
- plugins/ui/source/ui/text_editor/editor.cpp
- plugins/ui/source/ui/text_editor/navigate.cpp
- plugins/ui/source/ui/text_editor/render.cpp
- plugins/ui/source/ui/text_editor/support.cpp
- plugins/ui/source/ui/text_editor/utf8.cpp
Fixed by only processing text that's visible.
Also fixed the cursor jumping to breakpoint line when selected by clicking the line number and added highlighting of the current editing line. An optimization that caches the number of utf-8 chars in each line was included as well.
Finally, an error that caused ImHex to crash if a pattern was saved as itself was also fixed.
> Fix: Very long lines in text editor could make it hang. 

- plugins/ui/source/ui/text_editor/navigate.cpp
When I implemented the changes to allow creating breakpoints without losing focus in the pattern editor and without forcing it to scroll to the cursor position I broke the code that ensures the cursor is visible after being moved to the source code that caused the error. All I needed to do is to explicitly set the argument because the default is to not scroll to the cursor when focus is given to the pattern editor
> fix: No scrolling on jumping to error source.
